server:
  port: 8080

jwt:
  secret: ks93w6IjKBc8TckMt9xjYSj2rE8YHJvduMBJiXBytHk=

spring:
  application:
    name: foodandmart

  datasource:
    url: jdbc:postgresql://187.127.156.147:5431/fm_db
    username: fm_user
    password: fm_password
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  instance:
    preferIpAddress: true

  client:
    fetchRegistry: true
    registerWithEureka: true

    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true

    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

google:
  maps:
    api-key: nZCbR3no1OICYxQMqhoN0DWl-go=