server:
  port: 8080
  #forward-headers-strategy: framework

jwt:
  secret: ks93w6IjKBc8TckMt9xjYSj2rE8YHJvduMBJiXBytHk=

spring:
  application:
    name: foodandmart

  data:
    redis:
      #password: jippy-redis@574
      #host: 187.127.156.147
      #port: 6379
      host: ${REDIS_HOST:jippy_redis}
      port: ${REDIS_PORT:6379}
      password: "${REDIS_PASSWORD:jippy-redis@574}"
      timeout: 6000ms

  datasource:
    url: jdbc:postgresql://187.127.156.147:5431/fm_db
    username: fm_user
    password: fm_password
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true




  mail:
    host: email-smtp.ap-south-1.amazonaws.com # Replace with your specific SES region endpoint
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



eureka:
  instance:
    preferIpAddress: true

  client:
    fetchRegistry: true
    registerWithEureka: true

    serviceUrl:
      defaultZone: http://eureka-admin:eureka-admin123@localhost:8070/eureka/

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Capture 100% of traces for development. Reduce in production (e.g., 0.1).
    otlp:
      endpoint: http://187.127.156.147:4317
      # Explicitly forces the app to use gRPC stream pipes over port 4317
      transport: grpc
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true

    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true


  logging:
    level:
      root: WARN                                      # Silences all general framework info spams globally
      org.springframework: WARN                       # Limits core spring internal operational logs
      com.netflix.discovery: WARN                     # Silences all Netflix/Eureka endpoint fetching logs
      com.jippy.foodandmart: INFO                     # KEEP: Ensures your own custom application business logs are still visible
    # Forces Spring Boot to append [Service-Name, TraceId, SpanId] into standard logs out-of-the-box
    include-application-name: true


google:
  maps:
    api-key: AIzaSyB6p_DgqwikOUxdpM3l6wbOxzFWRj5lkmg


springdoc:
  api-docs:
    path: /api/fm/v3/api-docs

product-content:
  admin-email: accounts@jippymart.in

aws:
  s3:
    bucket-name: jippys3bucket
    region: ap-south-2
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    product-content-file: product-content/master_products_descriptions_images.xlsx




