CREATE SCHEMA IF NOT EXISTS jippy_fm;

CREATE SCHEMA IF NOT EXISTS jippy_fm;
CREATE TABLE IF NOT EXISTS jippy_fm.state
(
    state_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    state_name character varying(50),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT state_pkey PRIMARY KEY (state_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.city
(
    city_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    city_name character varying(50),
    state_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT city_pkey PRIMARY KEY (city_id),
    CONSTRAINT city_state_fk_key FOREIGN KEY (state_id)
                REFERENCES jippy_fm.state(state_id)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION

);

CREATE TABLE IF NOT EXISTS jippy_fm.area
(
    area_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    area_name character varying(50),
    city_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT area_pkey PRIMARY KEY (area_id),
    CONSTRAINT area_city_fk_key FOREIGN KEY (city_id)
            REFERENCES jippy_fm.city(city_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.merchants
(
    merchant_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    merchant_name character varying(150),
    merchant_email character varying(150),
    merchant_phone character varying(20),
    merchant_business_type character varying(50),
    status character varying(30) DEFAULT 'PENDING',
    state character varying(30), -- Andhra Pradesh,Telangana
	created_at timestamp without time zone,
	created_by integer,
	updated_at timestamp without time zone,
	updated_by integer,
	is_active character varying(1) DEFAULT 'N',
	is_approved boolean NOT NULL DEFAULT false,
    CONSTRAINT merchants_pkey PRIMARY KEY (merchant_id),
    CONSTRAINT merchant_email UNIQUE (merchant_email),
    CONSTRAINT merchant_phone UNIQUE (merchant_phone)
);

CREATE TABLE IF NOT EXISTS jippy_fm.merchant_kyc
(
    kyc_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    merchant_id integer NOT NULL,
    pan_number character varying(20),
    aadhaar_number character varying(20),
    fssai_number character varying(30),
    gst_number character varying(30),
    verified boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT merchant_kyc_pkey PRIMARY KEY (kyc_id),
    CONSTRAINT merchant_kyc_merchant_fk_key FOREIGN KEY (merchant_id)
        REFERENCES jippy_fm.merchants (merchant_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.user_bank_details
(
    bank_id  integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    recipient_id integer NOT NULL, -- merchantId,driverId
    account_number character varying(30),
    ifsc_code character varying(15),
    bank_name character varying(100),
    account_holder_name character varying(150),
    user_type character varying(50),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT "merchant_bank_details _pkey" PRIMARY KEY (bank_id)

);

CREATE TABLE IF NOT EXISTS jippy_fm.employees
(
    employee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    mobile_number character varying(14),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_active character varying(1) DEFAULT 'Y',
    CONSTRAINT employees_pkey PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.permissions
(
    permission_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    permission_name character varying(100),
    created_by integer,
    created_at timestamp without time zone,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT permissions_pkey PRIMARY KEY (permission_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.roles
(
    role_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_name character varying(100),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.role_permissions
(
    role_permission_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_permission_id),
    CONSTRAINT fk_permission FOREIGN KEY (permission_id)
        REFERENCES jippy_fm.permissions (permission_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_role FOREIGN KEY (role_id)
        REFERENCES jippy_fm.roles (role_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS jippy_fm.users
(
    users_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100),
    password character varying(100),
    user_id integer NOT NULL,-- outletId,merchantId,driverId,customerId,employeeId
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_active character varying(1) DEFAULT 'N',
    user_type character varying(50), -- 'EMPLOYEE', 'MERCHANT', 'DRIVER', 'CUSTOMER','OUTLET'
    CONSTRAINT users_pkey PRIMARY KEY (users_id)

);

CREATE TABLE IF NOT EXISTS jippy_fm.user_role_permissions
(
    user_role_permission_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_permission_id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    CONSTRAINT user_role_permissions_pkey PRIMARY KEY (user_role_permission_id),
    CONSTRAINT fk_user_role_permission_id FOREIGN KEY (role_permission_id)
        REFERENCES jippy_fm.role_permissions (role_permission_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_user_role_permissions_fk FOREIGN KEY (user_id)
        REFERENCES jippy_fm.users (users_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS jippy_fm.approvals
(
    approvals_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    approval_type_id integer NOT NULL,
    entity_id integer NOT NULL, -- merchantId, -- outletId
    status integer,
    rejected_reason character varying(500),
    approved_by integer,
    approved_at timestamp without time zone,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT approvals_pkey PRIMARY KEY (approvals_id),
    CONSTRAINT approval_status_fk_key FOREIGN KEY (status)
        REFERENCES jippy_fm.status (status_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT approval_type_fk_key FOREIGN KEY (approval_type_id)
        REFERENCES jippy_fm.approval_types (approval_type_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.approvals
(
    approvals_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    business_approver_id integer NOT NULL,
    entity_id integer NOT NULL, -- merchantId, -- outletId
    status character varying(20), -- APPROVED, REJECTED, PENDING
    rejected_reason character varying(500),
    approved_by integer,
    approved_at timestamp without time zone,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT approvals_pkey PRIMARY KEY (approvals_id),
    CONSTRAINT approval_type_fk_key FOREIGN KEY (business_approver_id)
        REFERENCES jippy_fm.business_approvers (business_approver_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlets
(
    outlet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_name character varying(100) NOT NULL,
    outlet_type character varying(30) NOT NULL, -- cloud kitchen, dine-in, takeaway
    merchant_id integer NOT NULL,
    cuisine_type character varying(100) NOT NULL,
    outlet_phone character varying(20) NOT NULL,
    radius NUMERIC(10, 2) NOT NULL DEFAULT 3.00,
    boundary GEOGRAPHY(POLYGON, 4326),
    outlet_location GEOGRAPHY(POINT, 4326),
    total_rating NUMERIC(2, 1),
    total_reviews integer DEFAULT 0,
    subscription_status character varying(20) DEFAULT false, -- subscribed, unsubscribed
    promotion_status character varying(20) DEFAULT false, -- promoted, not promoted
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_active character varying(1) DEFAULT 'Y',
    employee_id integer,
    is_approved boolean NOT NULL DEFAULT false,
    accepts_scheduled_orders boolean NOT NULL DEFAULT true,
    CONSTRAINT outlets_pkey PRIMARY KEY (outlet_id),
    CONSTRAINT outlet_merchant_fk_key FOREIGN KEY (merchant_id)
        REFERENCES jippy_fm.merchants (merchant_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE INDEX outlet_location_idx ON jippy_fm.outlets USING GIST (outlet_location);


CREATE TABLE IF NOT EXISTS jippy_fm.address
(
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    jippy_address_id integer NOT NULL, --outletId,merchantId,driverId
    building_number  character varying(50) NOT NULL,
    road  character varying(100) NOT NULL,
    landmark  character varying(150) NOT NULL,
    city_id integer NOT NULL,
    state_id  integer NOT NULL,
    area_id integer NOT NULL,
    address_type character varying(50) NOT NULL, -- outlet --merchant -- driver
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_address_pkey PRIMARY KEY (address_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.days_of_week
(
    day_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    day_name character varying(20) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT days_of_week_pkey PRIMARY KEY (day_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_days(
    outlet_day_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    day_of_week_id integer NOT NULL,
    is_open boolean NOT NULL DEFAULT true,
    opening_time time without time zone NOT NULL,
    closing_time time without time zone NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_days_pkey PRIMARY KEY (outlet_day_id),
    CONSTRAINT outlet_days_outlet_fk_key FOREIGN KEY (outlet_id)
        REFERENCES jippy_fm.outlets (outlet_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_fm.categories
(
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_name character varying(100) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_categories
(
    outlet_category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
	--is_available boolean,
    category_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_categories_pkey PRIMARY KEY (outlet_category_id),
     CONSTRAINT outlet_categories_fk_key FOREIGN KEY (outlet_id)
            REFERENCES jippy_fm.outlets (outlet_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
     CONSTRAINT outlet_category_category_fk_key FOREIGN KEY (category_id)
             REFERENCES jippy_fm.categories (category_id)
             ON UPDATE NO ACTION
             ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.products
(
    product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_category_id integer NOT NULL,
    product_name character varying(100) NOT NULL,
    description character varying(500) NOT NULL,
    merchant_price NUMERIC(10, 2) NOT NULL,
    is_veg  boolean NOT NULL DEFAULT true,
    has_product_variants boolean NOT NULL DEFAULT false,
    image_link TEXT,
    photos TEXT,
    thumbnail TEXT,
    -- is_available boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT products_pkey PRIMARY KEY (product_id),
     CONSTRAINT product_outlet_categories_fk_key FOREIGN KEY (outlet_category_id)
                 REFERENCES jippy_fm.outlet_categories (outlet_category_id)
                 ON UPDATE NO ACTION
                 ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.product_online_pricing
(
    product_online_pricing_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    outlet_category_id integer NOT NULL,
    online_price NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_approved boolean,
    approved_by integer,
    CONSTRAINT product_online_pricing_pkey PRIMARY KEY (product_online_pricing_id)

);

CREATE TABLE IF NOT EXISTS jippy_fm.product_variants
(
    product_variant_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    variant_name character varying(100) NOT NULL,
    merchant_price NUMERIC(10, 2) NOT NULL,
    -- is_available boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT product_variants_pkey PRIMARY KEY (product_variant_id),
     CONSTRAINT product_variants_fk_key FOREIGN KEY (product_id)
            REFERENCES jippy_fm.products (product_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.master_products(
    master_product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    master_product_name character varying(100) NOT NULL,
    description TEXT,
    short_description TEXT,
    photo TEXT,
    photos TEXT,
    thumbnail TEXT,
    category_id integer NOT NULL,
    category_name character varying(100) NOT NULL,
    sub_category_id integer,
    sub_category_name character varying(100),
    veg integer NOT NULL DEFAULT 0,
    non_veg integer NOT NULL DEFAULT 0,
    food_type character varying(50),
    cuisine_type character varying(100),
    calories integer DEFAULT 0,
    protein integer DEFAULT 0,
    fats integer DEFAULT 0,
    carbs integer DEFAULT 0,
    grams integer DEFAULT 0,
    --tags text,
    --display_order integer,
    --- is_available integer NOT NULL DEFAULT 0,
    has_options integer NOT NULL DEFAULT 0,
    options_enabled integer NOT NULL DEFAULT 0,
    options jsonb,
    publish integer NOT NULL DEFAULT 1,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT master_products_pkey PRIMARY KEY (master_product_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.product_available_timings(
    product_available_timing_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    day_of_week_id integer NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT product_available_timings_pkey PRIMARY KEY (product_available_timing_id),
     CONSTRAINT product_available_timings_product_fk_key FOREIGN KEY (product_id)
            REFERENCES jippy_fm.products (product_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.subscription_plans
(
    subscription_plan_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    plan_name character varying(100) NOT NULL, --
    price NUMERIC(10, 2) NOT NULL,
    duration_in_days integer NOT NULL DEFAULT 30,
    radius_in_kms NUMERIC(10,2) NOT NULL,
    banner_slots character varying(50),
    banner_days integer,
    best_restaurant_slot character varying(50),
    whatsapp_broadcast character varying(50),
    video_credits character varying(50),
    state_id integer,
    city_id integer,
    area_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT subscription_plans_pkey PRIMARY KEY (subscription_plan_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_subscription_plans
(
    outlet_subscription_plan_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    subscription_plan_id integer,
    subscription_from_date date,
    subscription_to_date date,
    banner_from_date date,
    banner_to_date date,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT merchant_subscription_plans_pkey PRIMARY KEY (subscription_plan_id),
     CONSTRAINT merchant_subscription_plans_merchant_fk_key FOREIGN KEY (outlet_id)
            REFERENCES jippy_fm.outlets (outlet_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.specialized_outlets(
    specialized_outlet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    state_id integer,
    city_id integer,
    area_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT specialized_outlets_pkey PRIMARY KEY (specialized_outlet_id),
     CONSTRAINT specialized_outlets_outlet_fk_key FOREIGN KEY (outlet_id)
            REFERENCES jippy_fm.outlets (outlet_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.nearest_stock_point(
    nearest_stock_point_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    specialized_outlet_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT nearest_stock_point_pkey PRIMARY KEY (nearest_stock_point_id),
    CONSTRAINT specialized_nearest_stock_point_fk_key FOREIGN KEY (specialized_outlet_id)
            REFERENCES jippy_fm.specialized_outlets (specialized_outlet_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_unavailability(
    outlet_unavailability_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    unavailability_id integer,--outletId,productId,categoryId
    unavailability_from_date date,
    unavailability_to_date date,
    type character varying(20), -- outlet, category, product
    reason character varying(500),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_unavailability_pkey PRIMARY KEY (outlet_unavailability_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_reviews(
    outlet_reviews_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    customer_id integer NOT NULL,
    rating integer NOT NULL, -- 1 to 5
    review_text character varying(500),
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_reviews_pkey PRIMARY KEY (outlet_reviews_id)
);


INSERT INTO jippy_fm.state(state_id, state_name, created_at, created_by)
	VALUES (1, 'ANDHRA PRADESH', now(), 1);

INSERT INTO jippy_fm.state(state_id, state_name, created_at, created_by)
	VALUES (2, 'TELANGANA', now(), 1);

INSERT INTO jippy_fm.city(city_id, city_name, state_id, created_at, created_by)
	VALUES (1, 'Vijayawada', 1, now(), 1);
INSERT INTO jippy_fm.city(city_id, city_name, state_id, created_at, created_by)
	VALUES (2, 'Guntur', 1, now(), 1);
INSERT INTO jippy_fm.city(city_id, city_name, state_id, created_at, created_by)
	VALUES (3, 'Hyderabad', 2, now(), 1);

INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (1, 'Benz circle', 1, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (2, 'MG Road', 1, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (3, 'Currency Nagar', 1, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (4, 'Managalgiri', 1, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (5, 'Bhavani Puram', 1, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (6, 'Gonnavaram', 1, now(), 1);

INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (7, 'Lakshmipuram', 2, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (8, 'Brodiepet', 2, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (9, 'Pattabhipuram', 2, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (10, 'Vidhyanagar', 2, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (11, 'Autonagar', 1, now(), 1);

INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (12, 'KPHB', 3, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (13, 'Kukatpally', 3, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (14, 'Nizampet', 3, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (15, 'Pragathi Nagar', 3, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (16, 'Ameerpet', 3, now(), 1);


INSERT INTO jippy_fm.roles(role_id, role_name, created_at) VALUES (1, 'SUPER ADMIN', now());
INSERT INTO jippy_fm.roles(role_id, role_name, created_at,created_by) VALUES (2, 'ADMIN', now(),1);
INSERT INTO jippy_fm.roles(role_id, role_name, created_at,created_by) VALUES (3, 'MERCHANT', now(),1);
INSERT INTO jippy_fm.roles(role_id, role_name, created_at,created_by) VALUES (4, 'OUTLET', now(),1);
INSERT INTO jippy_fm.roles(role_id, role_name, created_at,created_by) VALUES (5, 'CATADMIN', now(),1);

INSERT INTO jippy_fm.permissions(permission_id, permission_name, created_by, created_at)
	VALUES (1, 'READ', 1, now());
INSERT INTO jippy_fm.permissions(permission_id, permission_name, created_by, created_at)
	VALUES (2, 'WRITE', 1, now());
INSERT INTO jippy_fm.permissions(permission_id, permission_name, created_by, created_at)
	VALUES (3, 'CREATE', 1, now());

INSERT INTO jippy_fm.employees(employee_id, employee_name, email, mobile_number, created_at,is_active)
	VALUES (1, 'Mohan', 'Mohan@gmail.com', '9876897654', now(),'Y');

INSERT INTO jippy_fm.users(
	users_id, username, password, user_id, created_at, is_active, user_type)
	VALUES (1, 'superadmin', 'superadmin@123', 1, now(), 'Y', 'Y', 'EMPLOYEE');

INSERT INTO jippy_fm.role_permissions(
	role_permission_id, role_id, permission_id, created_at, created_by)
	VALUES (1, 3, 1, now(), 1);

INSERT INTO jippy_fm.role_permissions(
	role_permission_id, role_id, permission_id, created_at, created_by)
	VALUES (2, 4, 1, now(), 1);

INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (1, 'Monday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (2, 'Tuesday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (3, 'Wednesday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (4, 'Thursday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (5, 'Friday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (6, 'Saturday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (7, 'Sunday', now(), 1);

INSERT INTO "jippy_fm"."subscription_plans" ("subscription_plan_id", "plan_name", "price",  "radius_in_kms","created_at","created_by")
 VALUES (1,'Basic', 0, 3,now(),1);
INSERT INTO "jippy_fm"."subscription_plans" ("subscription_plan_id", "plan_name", "price",  "radius_in_kms","created_at","created_by")
 VALUES (2,'Premium', 1299, 5,now(),1);
 INSERT INTO "jippy_fm"."subscription_plans" ("subscription_plan_id", "plan_name", "price",  "radius_in_kms","created_at","created_by")
 VALUES (3,'Ultra', 1999, 7,now(),1);
 INSERT INTO "jippy_fm"."subscription_plans" ("subscription_plan_id", "plan_name", "price",  "radius_in_kms","created_at","created_by")
 VALUES (4,'Ultra Premium', 2299, 9,now(),1);
 INSERT INTO "jippy_fm"."subscription_plans" ("subscription_plan_id", "plan_name", "price",  "radius_in_kms","created_at","created_by")
 VALUES (5,'Advance', 3999, 10,now(),1);


alter table "jippy_fm"."outlets" add column is_toggle boolean default true;
alter table "jippy_fm"."outlet_categories" add column is_toggle boolean default true;
alter table "jippy_fm"."products" add column is_toggle boolean default true;