CREATE SCHEMA IF NOT EXISTS jippy_fm;
CREATE EXTENSION IF NOT EXISTS postgis;
--================================================================================
--========ANDROID / IOS VERSIONS For Mobile Applications =========================
--================================================================================
CREATE TABLE "jippy_fm"."app_settings" (
    app_settings_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app_name VARCHAR(100) NOT NULL,
    package_name VARCHAR(255) NOT NULL,
    app_type VARCHAR(50) NOT NULL,
    android_version VARCHAR(20),
    android_build VARCHAR(20),
    ios_version VARCHAR(20),
    ios_build VARCHAR(20),
    min_required_version VARCHAR(20) NOT NULL,
    latest_version VARCHAR(20) NOT NULL,
    android_update_url TEXT,
    ios_update_url TEXT,
    force_update BOOLEAN DEFAULT FALSE,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT app_settings_pkey PRIMARY KEY (app_settings_id)
);
--================================================================================
--=======================Terms And Conditions ====================================
--================================================================================
CREATE TABLE "jippy_fm"."terms_and_conditions" (
    terms_and_conditions_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app_type VARCHAR(50) NOT NULL UNIQUE,
    privacy_and_policy TEXT,
    terms_and_conditions TEXT,
    CONSTRAINT terms_and_conditions_pkey PRIMARY KEY (terms_and_conditions_id)
);
--===================================================================================
--===================================================================================
CREATE TABLE IF NOT EXISTS jippy_fm.state
(
    state_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    state_name character varying(50),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT state_pkey PRIMARY KEY (state_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.city
(
    city_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    city_name character varying(50),
    state_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT city_pkey PRIMARY KEY (city_id),
    CONSTRAINT city_state_fk_key FOREIGN KEY (state_id)
                REFERENCES jippy_fm.state(state_id)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION

);

CREATE TABLE IF NOT EXISTS jippy_fm.area
(
    area_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    area_name character varying(50),
    city_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT area_pkey PRIMARY KEY (area_id),
    CONSTRAINT area_city_fk_key FOREIGN KEY (city_id)
            REFERENCES jippy_fm.city(city_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.merchants
(
    merchant_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    merchant_name character varying(150),
    merchant_email character varying(150),
    merchant_phone character varying(20),
    merchant_business_type character varying(50),
    status character varying(30) DEFAULT 'PENDING',
    date_of_birth date,
	created_at timestamp without time zone,
	created_by integer,
	updated_at timestamp without time zone,
	updated_by integer,
	is_active character varying(1) DEFAULT 'N',
	is_approved boolean NOT NULL DEFAULT false,
	profile_pic_url character varying(100),
    CONSTRAINT merchants_pkey PRIMARY KEY (merchant_id),
    CONSTRAINT merchant_email UNIQUE (merchant_email),
    CONSTRAINT merchant_phone UNIQUE (merchant_phone)
);

CREATE TABLE IF NOT EXISTS jippy_fm.user_kyc
(
    kyc_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_id integer NOT NULL,
    entity_type character varying(30) NOT NULL,
    pan_number character varying(30),
    aadhaar_number character varying(30),
    fssai_number character varying(30),
    gst_number character varying(30),
    pan_number_url CHARACTER VARYING(500),
    aadhaar_number_url CHARACTER VARYING(500),
    fssai_number_url CHARACTER VARYING(500),
    gst_number_url CHARACTER VARYING(500),
    verified boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT user_kyc_pkey PRIMARY KEY (kyc_id),
    CONSTRAINT entity_id_entity_type_unique UNIQUE (entity_id,entity_type)
);

---- Drop only the foreign key constraint
--ALTER TABLE jippy_fm.user_kyc
--DROP CONSTRAINT merchant_kyc_merchant_fk_key;

CREATE TABLE IF NOT EXISTS jippy_fm.user_bank_details
(
    bank_id  integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    recipient_id integer NOT NULL, -- merchantId,driverId
    account_number character varying(30),
    ifsc_code character varying(20),
    bank_name character varying(100),
    account_holder_name character varying(150),
    user_type character varying(50),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT user_bank_details_pkey PRIMARY KEY (bank_id),
    CONSTRAINT recipient_id_user_type_unique UNIQUE (recipient_id,user_type)

);

CREATE TABLE IF NOT EXISTS jippy_fm.employees
(
    employee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_name character varying(100) NOT NULL,
    email character varying(100) NOT NULL UNIQUE,
    mobile_number character varying(14) UNIQUE,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_active character varying(1) DEFAULT 'Y',
    CONSTRAINT employees_pkey PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.permissions
(
    permission_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    permission_name character varying(100) UNIQUE,
    created_by integer,
    created_at timestamp without time zone,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT permissions_pkey PRIMARY KEY (permission_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.roles
(
    role_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_name character varying(100) UNIQUE,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.role_permissions
(
    role_permission_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_permission_id),
    CONSTRAINT fk_permission FOREIGN KEY (permission_id)
        REFERENCES jippy_fm.permissions (permission_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_role FOREIGN KEY (role_id)
        REFERENCES jippy_fm.roles (role_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS jippy_fm.users
(
    users_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100) UNIQUE,
    password character varying(100),
    user_id integer NOT NULL,-- outletId,merchantId,driverId,customerId,employeeId
    is_active character varying(1) DEFAULT 'N',
    user_type character varying(50), -- 'EMPLOYEE', 'MERCHANT', 'DRIVER', 'CUSTOMER','OUTLET'
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT users_pkey PRIMARY KEY (users_id),
    CONSTRAINT user_id_user_type_unique UNIQUE (user_id,user_type)

);

CREATE TABLE IF NOT EXISTS jippy_fm.user_role_permissions
(
    user_role_permission_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_permission_id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    CONSTRAINT user_role_permissions_pkey PRIMARY KEY (user_role_permission_id),
    CONSTRAINT fk_user_role_permission_id FOREIGN KEY (role_permission_id)
        REFERENCES jippy_fm.role_permissions (role_permission_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_user_role_permissions_fk FOREIGN KEY (user_id)
        REFERENCES jippy_fm.users (users_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS jippy_fm.approval_settings
(
    approval_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_type character varying(30) NOT NULL, -- merchant, -- outlet ,driver
    workflow_type character varying(20) NOT NULL DEFAULT 'CASCADE', --cascade,parallel
    approval_level INTEGER NOT NULL,               -- 1, 2, or 3,5-- auto approval
    approver_role CHARACTER VARYING(50) NULL, -- 'FLEET', 'ZONE_MANAGER', 'GENERAL_MANAGER'
    approver_id integer NULL, -- 55
    is_active BOOLEAN DEFAULT TRUE,
    time_to_escalate_in_hours integer, -- 24
    triggers_activation boolean DEFAULT FALSE, -- True if this level activates the outlet
    required_approvals_count integer null,
    created_by integer,
    created_at timestamp without time zone,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT approval_settings_pkey PRIMARY KEY (approval_settings_id),
    -- Constraint ensures a specific role or person can only be declared once per level for an entity
    CONSTRAINT uq_entity_level_assignee UNIQUE (entity_type, approval_level, approver_role, approver_id)

);

CREATE TABLE IF NOT EXISTS jippy_fm.approval_transactions
(
    approval_transactions_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_type character varying(30) NOT NULL, --MERCHANT OUTLET
    entity_id integer NOT NULL, -- merchantId, -- outletId
    approval_level integer NOT NULL, -- 1,2,3
    status character varying(30), -- 1st APPROVED, REJECTED
    rejected_reason character varying(500),
    approved_by integer NOT NULL,
    approved_at timestamp without time zone,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT approval_transactions_pkey PRIMARY KEY (approval_transactions_id),
    CONSTRAINT approval_transactions_unique UNIQUE (entity_type,entity_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.approval_requests (
    approval_request_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_type character varying(30) NOT NULL,  -- 'OUTLET'
    entity_id integer NOT NULL,                  -- The actual outlet_id
    current_level character varying(20) NOT NULL DEFAULT 'LEVEL 1',    -- Starts at level 1
    status character varying(30) NOT NULL,       -- 'PENDING', 'APPROVED', 'REJECTED'
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT approval_requests_pkey PRIMARY KEY (approval_request_id),
    -- Ensures an entity can only have one active approval workflow running at any given time
    CONSTRAINT uq_entity_active_request UNIQUE (entity_type, entity_id, status)
);

CREATE TABLE IF NOT EXISTS jippy_fm.manager_areas (
    manager_areas_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL, --55
    area_id integer NOT NULL, -- 3,8,9
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT manager_areas_pkey PRIMARY KEY (manager_areas_id),
    CONSTRAINT uq_entity_request UNIQUE (user_id, area_id),
    CONSTRAINT manager_areas_user_fk FOREIGN KEY (user_id) REFERENCES jippy_fm.users (users_id)
    ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT manager_areas_area_fk FOREIGN KEY (area_id) REFERENCES jippy_fm.area (area_id)
     ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlets
(
    outlet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_name character varying(100) NOT NULL,
    outlet_pic_url character varying(500),
    outlet_email character varying(50) NOT NULL UNIQUE,
    alternate_outlet_phone character varying(20),
    outlet_phone character varying(20) NOT NULL UNIQUE,
    outlet_type character varying(30) NOT NULL, -- cloud kitchen, dine-in, takeaway,mart
    merchant_id integer NOT NULL,
    cuisine_type integer[] NOT NULL,
    radius NUMERIC(10, 2) NOT NULL DEFAULT 3.00,
    --boundary GEOGRAPHY(POLYGON, 4326),
    outlet_location GEOGRAPHY(POINT, 4326),
    total_rating NUMERIC(2, 1),
    total_reviews integer DEFAULT 0,
    subscription_status character varying(20) DEFAULT false, -- subscribed, unsubscribed
    promotion_status character varying(20) DEFAULT false, -- promoted, not promoted
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_active character varying(1) DEFAULT 'Y',
    employee_id integer,
    is_approved boolean NOT NULL DEFAULT false,
    accepts_scheduled_orders boolean NOT NULL DEFAULT true,
    is_veg_outlet boolean not null default false,
    is_gst_applied boolean not null default false,
    is_toggle boolean not null default false,
    CONSTRAINT outlets_pkey PRIMARY KEY (outlet_id),
    CONSTRAINT outlet_merchant_fk_key FOREIGN KEY (merchant_id)
        REFERENCES jippy_fm.merchants (merchant_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE INDEX outlet_location_idx ON jippy_fm.outlets USING GIST (outlet_location);


CREATE TABLE IF NOT EXISTS jippy_fm.address
(
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    jippy_address_id integer NOT NULL, --outletId,merchantId,driverId
    building_number  character varying(500) NOT NULL,
    road  character varying(100),
    landmark  character varying(150),
    city_id integer NOT NULL,
    state_id  integer NOT NULL,
    area_id integer NOT NULL,
    address_type character varying(50) NOT NULL, -- outlet --merchant -- driver
    location GEOGRAPHY(POINT, 4326),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_address_pkey PRIMARY KEY (address_id),
    CONSTRAINT address_id_address_type_unique UNIQUE(jippy_address_id,address_type),
     CONSTRAINT address_city_fk FOREIGN KEY (city_id) REFERENCES jippy_fm.city (city_id)
      ON UPDATE NO ACTION
      ON DELETE NO ACTION,
     CONSTRAINT address_state_fk FOREIGN KEY (state_id) REFERENCES jippy_fm.state (state_id)
      ON UPDATE NO ACTION
      ON DELETE NO ACTION,
     CONSTRAINT address_area_fk FOREIGN KEY (area_id) REFERENCES jippy_fm.area (area_id)
     ON UPDATE NO ACTION
     ON DELETE NO ACTION
);



CREATE TABLE IF NOT EXISTS jippy_fm.days_of_week
(
    day_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    day_name character varying(20) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT days_of_week_pkey PRIMARY KEY (day_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_days(
    outlet_day_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    day_of_week_id integer NOT NULL,
    is_open boolean NOT NULL DEFAULT true,
    opening_time time without time zone NOT NULL,
    closing_time time without time zone NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_days_pkey PRIMARY KEY (outlet_day_id),
    CONSTRAINT outlet_id_day_of_week_id_unique UNIQUE(outlet_id,day_of_week_id),
    CONSTRAINT outlet_days_outlet_fk_key FOREIGN KEY (outlet_id)
        REFERENCES jippy_fm.outlets (outlet_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_fm.categories
(
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_name character varying(100) NOT NULL UNIQUE,
    category_type character varying(50) NOT NULL,
    category_image_url character varying(500),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_categories
(
    outlet_category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
	--is_available boolean,
    category_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_active character varying(1) NOT NULL DEFAULT 'Y',
    is_toggle boolean NOT NULL DEFAULT true,
    CONSTRAINT outlet_categories_pkey PRIMARY KEY (outlet_category_id),
     CONSTRAINT outlet_categories_fk_key FOREIGN KEY (outlet_id)
            REFERENCES jippy_fm.outlets (outlet_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
     CONSTRAINT outlet_category_category_fk_key FOREIGN KEY (category_id)
             REFERENCES jippy_fm.categories (category_id)
             ON UPDATE NO ACTION
             ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.products
(
    product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_category_id integer NOT NULL,
    product_name character varying(100) NOT NULL UNIQUE,
    description character varying(500) NOT NULL,
    merchant_price NUMERIC(10, 2) NOT NULL,
    is_veg  boolean NOT NULL DEFAULT true,
    has_product_variants boolean NOT NULL DEFAULT false,
    image_link TEXT,
    is_toggle boolean NOT NULL,
    is_active character varying(1) NOT NULL,
    rating NUMERIC(10, 2),
    is_image_desc_updated boolean,
    product_type character varying(20) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT products_pkey PRIMARY KEY (product_id),
     CONSTRAINT product_outlet_categories_fk_key FOREIGN KEY (outlet_category_id)
                 REFERENCES jippy_fm.outlet_categories (outlet_category_id)
                 ON UPDATE NO ACTION
                 ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.product_online_pricing
(
    product_online_pricing_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    outlet_category_id integer NOT NULL,
    product_variant_id integer,
    online_price NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_approved boolean,
    approved_by integer,
    CONSTRAINT product_online_pricing_pkey PRIMARY KEY (product_online_pricing_id),
     CONSTRAINT prod_online_pricing_product_fk FOREIGN KEY (product_id)
    REFERENCES jippy_fm.products (product_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
         CONSTRAINT prod_online_pricing_category_fk FOREIGN KEY (outlet_category_id)
        REFERENCES jippy_fm.outlet_categories (outlet_category_id)
        ON UPDATE NO ACTION
                         ON DELETE NO ACTION

);



CREATE TABLE IF NOT EXISTS jippy_fm.master_products(
    master_product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    master_product_name character varying(100) NOT NULL,
    description TEXT,
--    short_description TEXT,
    photo TEXT,
--    photos TEXT,
--    thumbnail TEXT,
    category_id integer NOT NULL,
    category_name character varying(100) NOT NULL,
--    sub_category_id integer,
--    sub_category_name character varying(100),
    is_veg boolean NOT NULL,
--    non_veg integer NOT NULL DEFAULT 0,
--    food_type character varying(50),
    cuisine_type character varying(100),
--    calories integer DEFAULT 0,
--    protein integer DEFAULT 0,
--    fats integer DEFAULT 0,
--    carbs integer DEFAULT 0,
--    grams integer DEFAULT 0,
    --tags text,
    --display_order integer,
    --- is_available integer NOT NULL DEFAULT 0,
    has_options integer NOT NULL DEFAULT 0,
--    options_enabled integer NOT NULL DEFAULT 0,
    options jsonb,
--    publish integer NOT NULL DEFAULT 1,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    product_type character varying(10) NOT NULL,
    is_active character varying(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT master_products_pkey PRIMARY KEY (master_product_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.product_available_timings(
    product_available_timing_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    day_of_week_id integer NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT product_available_timings_pkey PRIMARY KEY (product_available_timing_id),
     CONSTRAINT product_available_timings_product_fk_key FOREIGN KEY (product_id)
            REFERENCES jippy_fm.products (product_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.subscription_plans
(
    subscription_plan_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    plan_name character varying(100) NOT NULL, --
    price NUMERIC(10, 2) NOT NULL,
    duration_in_days integer NOT NULL DEFAULT 30,
    banner_duration_in_days integer,
    radius_in_kms NUMERIC(10,2) NOT NULL,
    banner_slot integer, ---3
    best_restaurant_slot integer,
    deals_slot integer,
    whatsapp_broadcast character varying(50),
    video_credits character varying(50),
    area_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT subscription_plans_pkey PRIMARY KEY (subscription_plan_id),
      CONSTRAINT banner_slot_unique UNIQUE (banner_slot),
      CONSTRAINT best_restaurant_slot UNIQUE (best_restaurant_slot),
      CONSTRAINT deals_slot UNIQUE (deals_slot)
);

-- Index for area filtering on plans
CREATE INDEX idx_subscription_plans_area
ON jippy_fm.subscription_plans (area_id);

CREATE TABLE IF NOT EXISTS jippy_fm.week_slot_days
(
    week_slot_days_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    slot_start_date date not null,
    slot_end_date date not null,
    slot_type character varying(30) not null,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT weak_slot_days_pkey PRIMARY KEY (week_slot_days_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_subscription_plans
(
    outlet_subscription_plan_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    subscription_plan_id integer,  -- 1,2,3
    banner_slot_days_id integer,  -- 1,2,3
    main_banner_url character varying(100),
    best_restaurant_banner_url character varying(100),
    deals_banner_url character varying(100),
    price_model_type character varying(50),
    offer_amount NUMERIC(10,2),
    meal_type_timings_ids integer[], ---[1,2,3,4]
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT merchant_subscription_plans_pkey PRIMARY KEY (outlet_subscription_plan_id),
    CONSTRAINT merchant_subscription_plans_merchant_fk_key FOREIGN KEY (outlet_id)
        REFERENCES jippy_fm.outlets (outlet_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT outlet_sub_plan_fk FOREIGN KEY (subscription_plan_id)
        REFERENCES jippy_fm.subscription_plans (subscription_plan_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT outlet_sub_slot_fk FOREIGN KEY (banner_slot_days_id)
        REFERENCES jippy_fm.week_slot_days (week_slot_days_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.specialized_outlets(
    specialized_outlet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    area_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT specialized_outlets_pkey PRIMARY KEY (specialized_outlet_id),
     CONSTRAINT specialized_outlets_outlet_fk_key FOREIGN KEY (outlet_id)
            REFERENCES jippy_fm.outlets (outlet_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
     CONSTRAINT spec_outlet_area_fk FOREIGN KEY (area_id)
     REFERENCES jippy_fm.area (area_id)
      ON UPDATE NO ACTION
      ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.nearest_stock_point(
    nearest_stock_point_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    specialized_outlet_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT nearest_stock_point_pkey PRIMARY KEY (nearest_stock_point_id),
    CONSTRAINT specialized_nearest_stock_point_fk_key FOREIGN KEY (specialized_outlet_id)
            REFERENCES jippy_fm.specialized_outlets (specialized_outlet_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_unavailability(
    outlet_unavailability_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    unavailability_id integer,--outletId,productId,categoryId
    unavailability_from_date date,
    unavailability_to_date date,
    type character varying(20), -- outlet, category, product
    reason character varying(500),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_unavailability_pkey PRIMARY KEY (outlet_unavailability_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.reviews(
    reviews_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    review_id integer NOT NULL, -- outletId, driverId
    customer_id integer NOT NULL,
    rating integer NOT NULL, -- 1 to 5
    review_text character varying(500),
    review_type character varying(20), -- Outlet, Driver
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT reviews_pkey PRIMARY KEY (reviews_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.cancelled_orders_inventory(
    cancelled_order_products_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    specialized_outlet_id integer NOT NULL,
    cancelled_order_id integer NOT NULL,
    driver_id integer NOT NULL,
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT cancelled_order_products_pkey PRIMARY KEY (cancelled_order_products_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.favorite_outlets(
    favorite_outlets_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    favorite_id integer NOT NULL, -- outlet_id, product_id
    favourite_type character varying(30),
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT favorite_outlets_id_pkey PRIMARY KEY (favorite_outlets_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.email_otp_verifications(
    email_otp_verifications_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_type character varying(30) NOT NULL, -- MERCHANT OUTLET
    entity_id integer, -- merchantId, outletId
    email character varying(100) NOT NULL,
    otp_hash character varying(255) NOT NULL,
    purpose character varying(255) NOT NULL, -- SIGNUP or FORGOT PASSWORD
    status character varying(100) NOT NULL, -- PENDING , VERIFIED,EXPIRED
    expires_at timestamp without time zone NOT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at timestamp without time zone,
    resend_count integer DEFAULT 0,
    no_of_attempts integer NOT NULL DEFAULT 1,
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT email_otp_verifications_pkey PRIMARY KEY (email_otp_verifications_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.meal_type_timings(
    meal_type_timings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    meal_type character varying(50) NOT NULL, -- Breakfast, Lunch, snacks,Dinner
    from_time time without time zone NOT NULL,
    to_time time without time zone NOT NULL,
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT  meal_type_timings_pkey PRIMARY KEY (meal_type_timings_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.promotion_plan_types(
    promotion_plan_types_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    plan_name character varying(30) NOT NULL, -- % offer, Flat offer, Time slot, 1+1 offer
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT promotion_plan_types_pkey PRIMARY KEY (promotion_plan_types_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.promotion_plans(
    promotion_plans_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    promotion_plan_types_id integer NOT NULL, -- % offer, Flat offer, Time slot, 1+1 offer
    plan_start_date date NOT NULL,
    plan_end_date date NOT NULL,
    plan_start_time time without time zone, -- only for timeslot
    plan_end_time time without time zone, --only for timeslot
    offer_name character varying(50) NOT NULL,
    minimum_order_value NUMERIC(10,2) NOT NULL,
    offer_amount NUMERIC(10,2) NOT NULL,
    offer_type character varying(20), --flat,percentage
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT promotion_plans_pkey PRIMARY KEY (promotion_plans_id),
    CONSTRAINT promotion_plans_fkey FOREIGN KEY (promotion_plan_types_id)
        REFERENCES jippy_fm.promotion_plan_types (promotion_plan_types_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT promo_plans_outlet_fk FOREIGN KEY (outlet_id)
     REFERENCES jippy_fm.outlets (outlet_id)
      ON UPDATE NO ACTION
             ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.promotion_plan_products(
    promotion_plan_products_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    promotion_plans_id integer NOT NULL,
    outlet_category_id integer NULL, --when merchant selects category id
    product_id integer NULL, -- when merchant selects product id
    max_selection integer NOT NULL DEFAULT -1, --means unlimited
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT promotion_plan_products_pkey PRIMARY KEY (promotion_plan_products_id),
    CONSTRAINT promotion_plan_products_fkey FOREIGN KEY (promotion_plans_id)
            REFERENCES jippy_fm.promotion_plans (promotion_plans_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,

    CONSTRAINT promo_products_category_fk FOREIGN KEY (outlet_category_id)
            REFERENCES jippy_fm.outlet_categories (outlet_category_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,

    CONSTRAINT promo_products_product_fk FOREIGN KEY (product_id)
            REFERENCES jippy_fm.products (product_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.product_variant_groups(
    product_variant_groups_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    group_name character varying(100) NOT NULL, -- size,portion,pack size,extras,crust
    selection_time character varying(20) NOT NULL, -- single /multiple   only extras has multiple
    min_selection integer NOT NULL DEFAULT 0, --for size/portion/pack mandatory minimum has to select 1 For Extras 0 (optional)
    max_selection integer NOT NULL DEFAULT 1, -- 1 for any/ extras may have multiple
    display_order integer,
    is_active boolean DEFAULT true,
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT product_variant_groups_pkey PRIMARY KEY (product_variant_groups_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.product_variant_group_values(
    product_variant_group_values_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_variant_groups_id integer, --1
    variant_name character varying(50) NOT NULL, --small,medium,large
    is_active boolean DEFAULT true,
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT product_variant_group_values_pkey PRIMARY KEY (product_variant_group_values_id),
    CONSTRAINT promotion_plan_products_fkey FOREIGN KEY (product_variant_groups_id)
               REFERENCES jippy_fm.product_variant_groups (product_variant_groups_id)
               ON UPDATE NO ACTION
               ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_fm.product_variant_options(
    product_variant_options_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_variant_group_values_id integer NOT NULL,
    product_id integer NOT NULL,
    price_type character varying(20),   -- Additional, main
    variant_price NUMERIC(10,2) NOT NULL,
    is_active character varying(1) NOT NULL DEFAULT 'Y',
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT product_variant_options_pkey PRIMARY KEY (product_variant_options_id),
     CONSTRAINT product_variant_options_fkey FOREIGN KEY (product_variant_group_values_id)
                   REFERENCES jippy_fm.product_variant_group_values (product_variant_group_values_id)
                   ON UPDATE NO ACTION
                   ON DELETE NO ACTION,
          CONSTRAINT prod_var_opt_product_fk FOREIGN KEY (product_id)
         REFERENCES jippy_fm.products (product_id)
           ON UPDATE NO ACTION
                            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.order_analysis_settings(
   order_analysis_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   min_no_of_rejected_orders integer NOT NULL,
   min_no_of_unavailability_slots integer NOT null,
   min_no_of_orders integer NOT NULL,
   created_by integer,
   created_at timestamp without time zone,
   updated_at timestamp without time zone,
   updated_by integer,
   CONSTRAINT order_analysis_settings_pkey PRIMARY KEY (order_analysis_settings_id)
);

CREATE TABLE jippy_fm.product_price_settings (
    product_price_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    product_variant_options_id INTEGER,
    start_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    price_value NUMERIC(12, 2) NOT NULL,
    price_type VARCHAR(20) NOT NULL,
    price_adjustment VARCHAR(20),
    location_id INTEGER NOT NULL,
    location_type VARCHAR(20),
    is_active character varying(1) NOT NULL,
    created_by INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by INTEGER,
    CONSTRAINT product_price_settings_pkey PRIMARY KEY (product_price_settings_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.product_price_change_history(
    product_price_change_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    product_id integer,
    product_variant_id integer,
    price_type character varying(10), -- MERCHANT,ONLINE
    start_date_time timestamp without time zone,
    end_date_time timestamp without time zone,
    old_price NUMERIC(10,2) NOT NULL,
    new_price NUMERIC(10,2) NOT NULL,
    location_id integer,
    location_type character varying(20), --city,state,area
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    operation_type character varying(20), --APPLY,RESTORE
    CONSTRAINT product_price_change_history_pkey PRIMARY KEY (product_price_change_history_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.merchant_price_change_history(
    merchant_price_change_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    product_id integer,
    product_variant_options_id integer,
    old_price NUMERIC(10,2) NOT NULL,
    new_price NUMERIC(10,2) NOT NULL,
    price_updated_by character varying(30),
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT merchant_price_change_history_pkey PRIMARY KEY (merchant_price_change_history_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.cuisine_types
(
    cuisine_types_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cuisine_types_name character varying(50) UNIQUE NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT cuisine_types_pkey PRIMARY KEY (cuisine_types_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.best_restaurants
(
    best_restaurants_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT best_restaurants_pkey PRIMARY KEY (best_restaurants_id),
     CONSTRAINT best_restaurants_outlet_fk FOREIGN KEY (outlet_id)
    REFERENCES jippy_fm.outlets (outlet_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.cuisine_types
(
    cuisine_types_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cuisine_types_name character varying(50) UNIQUE NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT cuisine_types_pkey PRIMARY KEY (cuisine_types_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.best_restaurants
(
    best_restaurants_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT best_restaurants_pkey PRIMARY KEY (best_restaurants_id),
    ADD CONSTRAINT best_restaurants_outlet_fk FOREIGN KEY (outlet_id)
    REFERENCES jippy_fm.outlets (outlet_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

CREATE TABLE jippy_fm.user_otp (
    user_otp_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    user_type VARCHAR(30) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    otp_type VARCHAR(30) NOT NULL DEFAULT 'LOGIN',
    otp_hash VARCHAR(255) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    resend_count INTEGER NOT NULL DEFAULT 0,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMP NOT NULL,
    last_attempt_at TIMESTAMP,
    verified_at TIMESTAMP,
    used_at TIMESTAMP,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER,
    updated_at timestamp without time zone,
    updated_by INTEGER,
    CONSTRAINT chk_user_otp_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT chk_user_otp_resend_count
        CHECK (resend_count >= 0),
    CONSTRAINT user_otp_pkey PRIMARY KEY (user_otp_id),
    CONSTRAINT user_id_user_type_unique UNIQUE(user_id,user_type)
);

INSERT INTO jippy_fm.state(state_id, state_name, created_at, created_by)
	VALUES (1, 'ANDHRA PRADESH', now(), 1);

INSERT INTO jippy_fm.state(state_id, state_name, created_at, created_by)
	VALUES (2, 'TELANGANA', now(), 1);

INSERT INTO jippy_fm.city(city_id, city_name, state_id, created_at, created_by)
	VALUES ( 'Vijayawada', 1, now(), 1);
INSERT INTO jippy_fm.city(city_id, city_name, state_id, created_at, created_by)
	VALUES (2, 'Guntur', 1, now(), 1);
INSERT INTO jippy_fm.city(city_id, city_name, state_id, created_at, created_by)
	VALUES (3, 'Hyderabad', 2, now(), 1);

INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (1, 'Benz circle', 1, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (2, 'MG Road', 1, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (3, 'Currency Nagar', 1, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (4, 'Managalgiri', 1, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (5, 'Bhavani Puram', 1, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (6, 'Gonnavaram', 1, now(), 1);

INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (7, 'Lakshmipuram', 2, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (8, 'Brodiepet', 2, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (9, 'Pattabhipuram', 2, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (10, 'Vidhyanagar', 2, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (11, 'Autonagar', 1, now(), 1);

INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (12, 'KPHB', 3, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (13, 'Kukatpally', 3, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (14, 'Nizampet', 3, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (15, 'Pragathi Nagar', 3, now(), 1);
INSERT INTO jippy_fm.area(area_id, area_name, city_id, created_at, created_by)
	VALUES (16, 'Ameerpet', 3, now(), 1);


INSERT INTO jippy_fm.roles(role_name, created_at) VALUES (1, 'ROLE_SUPERADMIN', now());
INSERT INTO jippy_fm.roles(role_name, created_at) VALUES (2, 'ROLE_ADMIN', now());
INSERT INTO jippy_fm.roles(role_name, created_at) VALUES (3, 'ROLE_MERCHANT', now());
INSERT INTO jippy_fm.roles(role_name, created_at) VALUES (4, 'ROLE_OUTLET', now());
INSERT INTO jippy_fm.roles(role_name, created_at) VALUES (5, 'ROLE_CATADMIN', now());
INSERT INTO jippy_fm.roles(role_name, created_at) VALUES (5, 'ROLE_CUSTOMER', now());
INSERT INTO jippy_fm.roles (role_name, created_at) VALUES ('ROLE_DRIVER', now());

INSERT INTO jippy_fm.permissions( permission_name, created_by, created_at)
	VALUES ( 'READ', 1, now());
INSERT INTO jippy_fm.permissions( permission_name, created_by, created_at)
	VALUES ('WRITE', 1, now());
INSERT INTO jippy_fm.permissions( permission_name, created_by, created_at)
	VALUES ( 'CREATE', 1, now());

INSERT INTO jippy_fm.users(
	 username, password, user_id, created_at, is_active, user_type)
	VALUES ('superadmin', '$2a$12$UkqllnNN3CB6nJMM3wGKhuXLB8KhSPWjPCFAaTnA86GCYxB0DVJ6S', 1, now(), 'Y', 'EMPLOYEE');

INSERT INTO jippy_fm.role_permissions(
	 role_id, permission_id, created_at, created_by)
	VALUES ( 3, 1, now(), 1);

INSERT INTO jippy_fm.role_permissions(
	 role_id, permission_id, created_at, created_by)
	VALUES ( 4, 1, now(), 1);


INSERT INTO jippy_fm.role_permissions(
	 role_id, permission_id, created_at)
	VALUES (1, 1, now());

INSERT INTO "jippy_fm"."user_role_permissions" ( "role_permission_id", "user_id", "created_at")
 VALUES ( 3, 1, now());

INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (1, 'Monday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (2, 'Tuesday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (3, 'Wednesday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (4, 'Thursday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (5, 'Friday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (6, 'Saturday', now(), 1);
INSERT INTO jippy_fm.days_of_week(
	day_id, day_name, created_at, created_by)
	VALUES (7, 'Sunday', now(), 1);

INSERT INTO "jippy_fm"."subscription_plans" ("subscription_plan_id", "plan_name", "price",  "radius_in_kms","created_at","created_by")
 VALUES (1,'Basic', 0, 3,now(),1);
INSERT INTO "jippy_fm"."subscription_plans" ("subscription_plan_id", "plan_name", "price",  "radius_in_kms","created_at","created_by")
 VALUES (2,'Premium', 1299, 5,now(),1);
 INSERT INTO "jippy_fm"."subscription_plans" ("subscription_plan_id", "plan_name", "price",  "radius_in_kms","created_at","created_by")
 VALUES (3,'Ultra', 1999, 7,now(),1);
 INSERT INTO "jippy_fm"."subscription_plans" ("subscription_plan_id", "plan_name", "price",  "radius_in_kms","created_at","created_by")
 VALUES (4,'Ultra Premium', 2299, 9,now(),1);
 INSERT INTO "jippy_fm"."subscription_plans" ("subscription_plan_id", "plan_name", "price",  "radius_in_kms","created_at","created_by")
 VALUES (5,'Advance', 3999, 10,now(),1);

 INSERT INTO "jippy_fm"."employees" ( "employee_name", "email", "mobile_number", "created_at",  "is_active")
  VALUES ( 'Mohan','superadmin@gmail.com', '9898768990', now(), 'Y');


