server:
  port: 8084

jwt:
  secret: ks93w6IjKBc8TckMt9xjYSj2rE8YHJvduMBJiXBytHk=
spring:
  application:
   name: gatewayserver
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
springdoc:
 enable-native-support: true
  # This helps the gateway discover routes from Eureka
 api-docs:
   enabled: true
   #gateway:
    # use-management-port: false
     #infer-routing-from-path: true
 webflux:
      # This ensures WebFlux handles the static UI paths cleanly
      all-disabled: false
 swagger-ui:
   path: /swagger-ui.html
     # Keeps the UI active
   enabled: true
     # ADD THIS LINE TO HIDE THE SCHEMAS SECTION:
   default-models-expand-depth: -1
   # This enables the "Select a definition" dropdown
   urls:
     - name: Notification Service
       url: /api/notification/v3/api-docs
     - name: Food And Mart Service
       url: /api/fm/v3/api-docs
     - name: division Service
       url: /api/div/v3/api-docs
     - name: customer and order Service
       url: /api/co/v3/api-docs
     - name: driver Service
       url: /api/driver/v3/api-docs



eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-admin:eureka-admin123@localhost:8070/eureka/

management:
  tracing:
    sampling:
      probability: 1.0 # Capture 100% of traces for development. Reduce in production (e.g., 0.1).
  otlp:
    tracing:
      #endpoint: http://localhost:4317 # The OTLP gRPC endpoint exposed by Grafana Tempo
  endpoints:
    web:
      exposure:
        include: "*"
  logging:
    level:
      root: WARN                                      # Silences all general framework info spams globally
      org.springframework: WARN                       # Limits core spring internal operational logs
      com.netflix.discovery: WARN                     # Silences all Netflix/Eureka endpoint fetching logs
      com.jippy.gatewayserver: INFO                     # KEEP: Ensures your own custom application business logs are still visible
    # Forces Spring Boot to append [Service-Name, TraceId, SpanId] into standard logs out-of-the-box
    include-application-name: true