CREATE SCHEMA IF NOT EXISTS jippy_notification;

CREATE TABLE  IF NOT EXISTS jippy_notification.notifications(
    notification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    notification_type character varying(50) NOT NULL, --NEW_ORDER,ORDER_DELIVERED,ORDER_ACCEPTED,CAMPAIGN,WALLET_CREDITED,WELCOME_POINTS_EARNED,REFERRAL_POINTS_EARNED
    role character varying(100) NOT NULL, -- outlet,driver,admin,customer
    subject character varying(100) NOT NULL, -- order notification,
    message character varying(100) NOT NULL,
    image_url character varying(1000),
    is_active boolean,
    priority  character varying(20),  -- LOW, MEDIUM, HIGH, CRITICAL
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);


CREATE TABLE IF NOT EXISTS jippy_notification.order_notification_status(
    order_notification_status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id character varying(30), -- NULL IN case of campaigns
    reference_id integer, -- campaign id
    reference_type character varying(50), --campaigns
    notification_id integer NOT NULL, -- placed, delivered, cancelled
    notification_recipient_id integer NOT NULL, -- outlet_id, driver_id, customer_id
    recipient_type character varying(30) NOT NULL, -- outlet, driver, customer
    notification_status boolean DEFAULT false, -- false means notification is not sent, true means notification is sent
    device_token_id integer NOT NULL,
    firebase_messaging_id character varying(500),
    sent_at TIMESTAMP,
    delivered_at TIMESTAMP,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT order_notification_status_pkey PRIMARY KEY (order_notification_status_id),
    CONSTRAINT order_notification_status_notification_id_fkey FOREIGN KEY (notification_id)
        REFERENCES jippy_notification.notifications (notification_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
    );

CREATE TABLE IF NOT EXISTS jippy_notification.wallet_notification_status(
    wallet_notification_status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id character varying(30),
    reference_id integer,
    reference_type character varying(50),
    notification_id integer NOT NULL,
    notification_recipient_id integer NOT NULL,
    recipient_type character varying(30) NOT NULL,
    notification_status boolean DEFAULT false,
    device_token_id integer NOT NULL,
    firebase_message_id character varying(500),
    sent_at TIMESTAMP,
    delivered_at TIMESTAMP,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT wallet_notification_status_pkey PRIMARY KEY (wallet_notification_status_id),
    CONSTRAINT wallet_notification_status_notification_id_fkey FOREIGN KEY (notification_id)
        REFERENCES jippy_notification.notifications (notification_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
    );


CREATE TABLE jippy_notification.device_tokens (
    device_token_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,                          -- Holds customer_id, driver_id, or merchant_id
    user_type VARCHAR(20) NOT NULL,                -- 'CUSTOMER', 'DRIVER', 'MERCHANT'
    fcm_token VARCHAR(500) NOT NULL,
    device_type VARCHAR(20),                       -- 'ANDROID', 'IOS'
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT device_tokens_pkey PRIMARY KEY (device_token_id),
    -- Prevents duplicate entries for the same user-role-device combination
    CONSTRAINT unique_user_device UNIQUE (user_id, user_type, fcm_token)
);
-- Index for fast lookups when sending notifications
CREATE INDEX idx_device_tokens_lookup
ON jippy_customer_and_order.device_tokens (user_id, user_type);
