
-- ============================================================
-- 1. SCHEMA
-- ============================================================

CREATE SCHEMA IF NOT EXISTS jippy_notification;


-- ============================================================
-- 2. NOTIFICATIONS
--
-- Master notification/template definitions.
--
-- Examples:
-- ORDER_PLACED
-- RESTAURANT_ACCEPTED
-- FOOD_PREPARING
-- DRIVER_ASSIGNED
-- WALLET_POINTS_EARNED
-- CUSTOMER_PROMOTIONAL_OFFER
-- ============================================================

CREATE TABLE IF NOT EXISTS jippy_notification.notifications (

    notification_id INTEGER NOT NULL
        GENERATED BY DEFAULT AS IDENTITY,

    notification_type VARCHAR(50) NOT NULL,

    role VARCHAR(100) NOT NULL,

    subject VARCHAR(100) NOT NULL,

    message VARCHAR(100) NOT NULL,

    image_url VARCHAR(1000),

    is_active BOOLEAN DEFAULT TRUE,

    priority VARCHAR(20),

    created_at TIMESTAMP WITHOUT TIME ZONE
        DEFAULT CURRENT_TIMESTAMP,

    created_by INTEGER,

    updated_at TIMESTAMP WITHOUT TIME ZONE,

    updated_by INTEGER,

    CONSTRAINT notifications_pkey
        PRIMARY KEY (notification_id),

    CONSTRAINT uk_notification_type_role
        UNIQUE (notification_type, role)
);


-- ============================================================
-- 3. DEVICE TOKENS
--
-- Stores FCM tokens for all user types.
--
-- One user can have MULTIPLE devices.
--
-- Example:
--
-- CUSTOMER 101
--     ├── Android → token-A
--     ├── iOS     → token-B
--     └── Web     → token-C
--
-- Every registered device receives the notification.
-- ============================================================

CREATE TABLE IF NOT EXISTS jippy_notification.device_tokens (

    device_token_id INTEGER NOT NULL
        GENERATED BY DEFAULT AS IDENTITY,

    user_id INTEGER NOT NULL,

    user_type VARCHAR(20) NOT NULL,

    fcm_token VARCHAR(500) NOT NULL,

    device_type VARCHAR(20),

    created_at TIMESTAMP WITHOUT TIME ZONE
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT device_tokens_pkey
        PRIMARY KEY (device_token_id),

    CONSTRAINT unique_user_device
        UNIQUE (
            user_id,
            user_type,
            fcm_token
        )
);


-- ============================================================
-- DEVICE TOKEN LOOKUP INDEX
--
-- Used when sending notification to all devices
-- belonging to a user.
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_device_tokens_lookup
ON jippy_notification.device_tokens (
    user_id,
    user_type
);


-- ============================================================
-- 4. ORDER NOTIFICATION STATUS
--
-- One row PER DEVICE for every order notification attempt.
--
-- Example:
--
-- Customer 101
-- Order ORD10001
--
-- device 10 → SUCCESS
-- device 11 → SUCCESS
-- device 12 → FAILED
--
-- Each device gets its own audit record.
-- ============================================================

CREATE TABLE IF NOT EXISTS jippy_notification.order_notification_status (

    order_notification_status_id INTEGER NOT NULL
        GENERATED BY DEFAULT AS IDENTITY,

    order_id VARCHAR(30),

    reference_id INTEGER,

    reference_type VARCHAR(50),

    notification_id INTEGER NOT NULL,

    notification_recipient_id INTEGER NOT NULL,

    recipient_type VARCHAR(30) NOT NULL,

    notification_status BOOLEAN DEFAULT FALSE,

    device_token_id INTEGER NOT NULL,

    firebase_message_id VARCHAR(500),

    sent_at TIMESTAMP,

    delivered_at TIMESTAMP,

    created_at TIMESTAMP WITHOUT TIME ZONE
        DEFAULT CURRENT_TIMESTAMP,

    created_by INTEGER,

    updated_at TIMESTAMP WITHOUT TIME ZONE,

    updated_by INTEGER,

    CONSTRAINT order_notification_status_pkey
        PRIMARY KEY (order_notification_status_id),

    CONSTRAINT order_notification_status_notification_id_fkey
        FOREIGN KEY (notification_id)
        REFERENCES jippy_notification.notifications (
            notification_id
        )
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


-- ============================================================
-- 5. WALLET NOTIFICATION STATUS
--
-- One row PER DEVICE for every wallet notification attempt.
--
-- Examples:
-- WALLET_POINTS_EARNED
-- POINTS_CONVERTED_TO_MONEY
-- REFERRAL_POINTS_EARNED
-- ============================================================

CREATE TABLE IF NOT EXISTS jippy_notification.wallet_notification_status (

    wallet_notification_status_id INTEGER NOT NULL
        GENERATED BY DEFAULT AS IDENTITY,

    order_id VARCHAR(30),

    reference_id INTEGER,

    reference_type VARCHAR(50),

    notification_id INTEGER NOT NULL,

    notification_recipient_id INTEGER NOT NULL,

    recipient_type VARCHAR(30) NOT NULL,

    notification_status BOOLEAN DEFAULT FALSE,

    device_token_id INTEGER NOT NULL,

    firebase_message_id VARCHAR(500),

    sent_at TIMESTAMP,

    delivered_at TIMESTAMP,

    created_at TIMESTAMP WITHOUT TIME ZONE
        DEFAULT CURRENT_TIMESTAMP,

    created_by INTEGER,

    updated_at TIMESTAMP WITHOUT TIME ZONE,

    updated_by INTEGER,

    CONSTRAINT wallet_notification_status_pkey
        PRIMARY KEY (wallet_notification_status_id),

    CONSTRAINT wallet_notification_status_notification_id_fkey
        FOREIGN KEY (notification_id)
        REFERENCES jippy_notification.notifications (
            notification_id
        )
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
-- Index for fast lookups when sending notifications
CREATE INDEX idx_device_tokens_lookup
ON jippy_customer_and_order.device_tokens (user_id, user_type);
