CREATE SCHEMA IF NOT EXISTS jippy_customer_and_order;

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.payment_mode(
    payment_mode_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    payment_mode character varying(50) NOT NULL, -- COD,razor
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT payment_mode_pkey PRIMARY KEY (payment_mode_id)

);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.application_versions(
    version_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    application_type character varying(50) NOT NULL, -- customer_app, outlet_app, driver_app
    version_number character varying(20) NOT NULL,--v1,v2,v3
    api_url character varying(100),
    api_version character varying(20),
    api_functionality character varying(100),
    db_query TEXT,
    db_query_version character varying(20),driver
    is_active BOOLEAN,
    is_approved BOOLEAN,
    environment character varying(20) NOT NULL, -- production, testing,development
    created_at timestamp without time zone,
    created_by integer,
    CONSTRAINT application_versions_pkey PRIMARY KEY (version_id),
    CONSTRAINT application_version_unique UNIQUE (application_type, version_number)
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_status(
    customer_status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    status_name character varying(20) NOT NULL, -- new,existing_coupons_applied,
    --existing_coupons_not_applied,existing_order_count
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_status_pkey PRIMARY KEY (customer_status_id),
    CONSTRAINT status_name UNIQUE (status_name)
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer(
    customer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50),
    email character varying(100),
    phone_number character varying(15) NOT NULL,
    date_of_birth date,
    customer_status_id integer,
    referral_code character varying(20),
    profile_pic_url character varying(100) NULL,
    area_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_pkey PRIMARY KEY (customer_id),
    CONSTRAINT email UNIQUE (email)
);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_delivery_addresses(
    customer_address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    location GEOGRAPHY(POINT),
    door_no character varying(30),
    building_name character varying(30),
    lane_no character varying(30),
    area integer,
    city integer,
    customer_location GEOGRAPHY(POINT, 4326),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_address_pkey PRIMARY KEY (customer_address_id)

);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_cart(
    cart_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_cart_pkey PRIMARY KEY (cart_id),
    CONSTRAINT customer_cart_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_coupons(
    customer_coupon_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    coupon_id integer NOT NULL,
    order_id character varying(30),
    is_redeemed BOOLEAN DEFAULT FALSE,
    redeemed_at timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_coupons_pkey PRIMARY KEY (customer_coupon_id),
    CONSTRAINT customer_coupons_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION

);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_points_history(
    points_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    points integer NOT NULL,
    points_source character varying(50) NOT NULL, -- company_points, referral_points, daily_streaks, deals
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT points_transaction_pkey PRIMARY KEY (points_history_id),
    CONSTRAINT points_transaction_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_wallet(
    wallet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer,
    balance_amount NUMERIC(10, 2) DEFAULT 0, -- minimum 1000 points
    balance_points integer DEFAULT 0,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_wallet_pkey PRIMARY KEY (wallet_id),
    CONSTRAINT customer_wallet_transaction_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_streaks(
    customer_streak_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    check_in_date date NOT NULL,
    current_streak integer DEFAULT 0, -- every day when logged in the value gets incremented by 1, if there is a break in the streak then it will be reset to 0 and start from first
    points integer DEFAULT 0,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT user_streaks_pkey PRIMARY KEY (customer_streak_id),
    CONSTRAINT user_streaks_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.order_sequence_manager(
    order_sequence_manager_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sequence_name character varying(30) NOT NULL,
    last_date DATE NOT NULL,
    current_seq integer NOT NULL,
     CONSTRAINT order_sequence_manager_pkey PRIMARY KEY (order_sequence_manager_id)
);
-- online price of selected products - merchant price on selected products in order-platform fee-delivery charges-gst = balance;
-- we will generate 2 coupons that is equal to balance(coupon should be applicable on coupon available restaurants);
-- if order is getting delayed by any reason beyond the estimated time, then increase estimated delivery time by adding current delivery time+half of current delivery time.
-- incase of driver reaching before deliver time to the customer, then we need to inform customer as we reached before estimated delivery time
CREATE TABLE IF NOT EXISTS jippy_customer_and_order.orders(
    order_id character varying(30) NOT NULL,
    customer_id integer NOT NULL,
    outlet_id integer NULL,
    driver_id integer,
    order_status character varying(20) NOT NULL, -- placed, delivered, cancelled
    --delivery_address character varying(500) NOT NULL,
    customer_delivery_address_id integer NOT NULL,
    customer_phone_number character varying(15) NOT NULL,
    preparation_time timestamp without time zone,
    estimated_delivery_time timestamp without time zone,
    distance_kms NUMERIC (10,2),
    payment_mode_id integer NOT NULL,
    order_type character varying(30) NOT NULL, --normal,scheduled,group_order,multi_order,home made
    scheduled_delivery_date_time timestamp without time zone, -- if order type is scheduled then it will have delivery date and time, if order type is normal then it will be null
    meal_subscription_id integer, -- if order is placed through meal subscription then it will have meal subscription id, otherwise it will be null
    group_order_invitation_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT orders_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.order_rejection(
    order_rejection_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id character varying(30) NOT NULL,
    rejected_by_id integer NOT NULL, -- driverId, outletId,customerId
    type character varying(20) NOT NULL, -- driver_rejection, outlet_rejection,customer_rejection
    reason  character varying(200)  NOT NULL,
    is_active BOOLEAN DEFAULT TRUE, -- default it is true, when customer paid make it false
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT order_rejection_pkey PRIMARY KEY (order_rejection_id),
     CONSTRAINT order_rejection_order_fk_key FOREIGN KEY (order_id)
            REFERENCES jippy_customer_and_order.orders (order_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION

);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.order_settings(
    order_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    platform_fee NUMERIC(10,2) NOT NULL,
    surge_fee NUMERIC(10,2) NOT NULL,
    packaging_fee NUMERIC(10,2) NOT NULL,
    delivery_fee_tax NUMERIC(10,2) NOT NULL, --18% tax on delivery fee
    food_total_amount_tax NUMERIC(10,2) NOT NULL, -- 5% tax on food total amount
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT order_settings_pkey PRIMARY KEY (order_settings_id)
);


CREATE  TABLE IF NOT EXISTS jippy_customer_and_order.fine_settings(
    fine_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fine_type character varying(50), --outlet, specialized outlet
    fine_amount NUMERIC(10, 2),
    cancelled_order_count integer NOT NULL,
    blacklist BOOLEAN DEFAULT FALSE, -- minimun 10 orders
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT fine_settings_pkey PRIMARY KEY (fine_settings_id)

);

CREATE  TABLE IF NOT EXISTS jippy_customer_and_order.recipient_fine(
    recipient_fine_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id character varying(30) NOT NULL,
    recipient_id integer NOT NULL, -- , outlet, customer
    recipient_type character varying(50) NOT NULL, -- outlet, customer
    fine_settings_id integer NOT NULL, --outlet, specialized outlet
    is_black_listed BOOLEAN DEFAULT FALSE,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT recipient_fine_pkey PRIMARY KEY (recipient_fine_id),
    CONSTRAINT recipient_fine_fk_key FOREIGN KEY (fine_settings_id)
            REFERENCES jippy_customer_and_order.fine_settings (fine_settings_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
     CONSTRAINT recipient_fine_order_fk_key FOREIGN KEY (order_id)
            REFERENCES jippy_customer_and_order.orders (order_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION

);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.order_items(
    order_item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id character varying(30) NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    merchant_unit_price NUMERIC(10, 2) NOT NULL,
    online_unit_price NUMERIC(10, 2) NOT NULL,
    online_price_total NUMERIC(10, 2) NOT NULL,
    merchant_price_total NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT orders_items_pkey PRIMARY KEY (order_item_id),
    CONSTRAINT order_items_order_fk_key FOREIGN KEY (order_id)
            REFERENCES jippy_customer_and_order.orders (order_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

 CREATE TABLE if not exists jippy_customer_and_order.order_price_breakup(
    order_price_breakup_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id character varying(30) NOT NULL,
    coupon_id integer,
    order_amount NUMERIC(10, 2) NOT NULL,
    platform_fee NUMERIC(10, 2),
    pick_up_distance_in_kms NUMERIC(10,2),
    delivery_distance_in_kms NUMERIC(10,2),
    pick_up_charges NUMERIC(10,2),
    deliver_charges NUMERIC(10,2),
    total_delivery_fee NUMERIC(10, 2),
    surge_fee NUMERIC(10, 2),
    packaging_fee NUMERIC(10, 2),
    gst NUMERIC(10, 2),
    order_total_amount NUMERIC(10, 2) NOT NULL,
    tip NUMERIC(10,2),
    coupon_discount NUMERIC(10, 2) DEFAULT 0,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT order_price_breakup_pkey PRIMARY KEY (order_price_breakup_id),
     CONSTRAINT order_price_breakup_order_fk_key FOREIGN KEY (order_id)
            REFERENCES jippy_customer_and_order.orders (order_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);
--added to prevent duplicate records of order id
ALTER TABLE jippy_customer_and_order.order_price_breakup
ADD CONSTRAINT unique_order_price UNIQUE (order_id);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver(
    driver_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    phone_number character varying(15) NOT NULL,
    email character varying(100),
    nominee_name character varying(50),
    nominee_phone_number character varying(15),
    is_nominee_verified BOOLEAN DEFAULT FALSE,
    family_member_name character varying(50),
    family_member_phone_number character varying(15),
    is_family_member_verified BOOLEAN DEFAULT FALSE,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_pkey PRIMARY KEY (driver_id)

);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_kyc(
    driver_kyc_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    aadhar_number character varying(20) NOT NULL,
    driving_license_number character varying(20) NOT NULL,
    rc_copy character varying(100) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_kyc_pkey PRIMARY KEY (driver_kyc_id),
     CONSTRAINT driver_kyc_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_delivery_charge_settings(
    delivery_charge_setting_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pick_up_kms_range_from NUMERIC(10,2) NOT NULL,
    pick_up_kms_range_to NUMERIC(10,2) NOT NULL,
    unit_price_per_pick_km NUMERIC(10, 2) NOT NULL,
    delivery_kms_range_from NUMERIC(10, 2) NOT NULL,
    delivery_kms_range_to NUMERIC(10, 2) NOT NULL,
    unit_price_per_deliver_km NUMERIC(10, 2) NOT NULL,
    --num_of_orders integer NOT NULL,
    -- incentives_amount NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_delivery_charge_settings_pkey PRIMARY KEY (delivery_charge_setting_id)
);

CREATE TABLE jippy_customer_and_order.zones (
    zone_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    zone_name VARCHAR(100),
    boundary GEOGRAPHY(POLYGON, 4326),
	created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT zones_pkey PRIMARY KEY (zone_id)
);
CREATE INDEX boundary_idx ON jippy_customer_and_order.zones USING GIST (boundary);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_incentive_settings(
    driver_incentive_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    orders_count integer NOT NULL,
    incentive_amount NUMERIC(10, 2) NOT NULL,
    zone_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_incentives_pkey PRIMARY KEY (driver_incentive_settings_id),
    CONSTRAINT driver_incentives_zone_fk_key FOREIGN KEY (zone_id)
                REFERENCES jippy_customer_and_order.zones (zone_id)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
);

CREATE TABLE if NOT EXISTS jippy_customer_and_order.driver_orders(
    driver_order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    order_id character varying(30) NOT NULL,
    pick_up_distance_in_kms NUMERIC(10,2),
    delivery_distance_in_kms NUMERIC(10,2),
    pick_up_charges NUMERIC(10,2),
    deliver_charges NUMERIC(10,2),
    total_delivery_fee NUMERIC(10, 2) NOT NULL, --100
    surge_fee NUMERIC(10,2), --20
    tips NUMERIC(10, 2), --10
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_order_id_pkey PRIMARY KEY (driver_order_id),
     CONSTRAINT driver_orders_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
     CONSTRAINT driver_orders_orders_fk_key FOREIGN KEY (order_id)
                 REFERENCES jippy_customer_and_order.orders (order_id)
                 ON UPDATE NO ACTION
                 ON DELETE NO ACTION
);



CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_zone_assignment(
    driver_zone_assignment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    zone_id integer NOT NULL,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT driver_zone_assignment_pkey PRIMARY KEY (driver_zone_assignment_id),
     CONSTRAINT driver_zone_assignment_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);





-- Track driver attendence daily
-- Fleet manager can track driver history.
-- Driver can not deliver orders though they are available, then we have to stop incentives.
--Driver settlements can be done in weekly 2 times, but incentives are done monthly once.
CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_history(
    driver_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    no_of_orders integer NOT NULL,
    last_login_date timestamp without time zone,
    available_from_time timestamp without time zone,
    available_to_time timestamp without time zone,
    created_at timestamp without time zone,order
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_history_pkey PRIMARY KEY (driver_history_id),
     CONSTRAINT driver_history_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_wallet(
    driver_wallet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    total_cod_amount NUMERIC(10, 2) DEFAULT 1000,-- if cod amount >=1000 then driver will not receive orders, driver needs to pay taht 1000rs to company account. Fleet manager can release the orders lock.
    orders_lock BOOLEAN DEFAULT false,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_wallet_pkey PRIMARY KEY (driver_wallet_id),
     CONSTRAINT driver_wallet_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);
--to prevent multiple wallet records for same driver
ALTER TABLE jippy_customer_and_order.driver_wallet
ADD CONSTRAINT unique_driver_wallet UNIQUE (driver_id);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_wallet_transactions(
    driver_wallet_transactions_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_wallet_id integer NOT NULL,
    order_id character varying(30) NOT NULL,
    cod_amount NUMERIC(10,2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_wallet_transactions_pkey PRIMARY KEY (driver_wallet_transactions_id),
     CONSTRAINT driver_wallet_transactions_fk_key FOREIGN KEY (driver_wallet_id)
            REFERENCES jippy_customer_and_order.driver_wallet (driver_wallet_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

-- if same customere placed 2 orders within 3kms from different outlets, then can we assign 2 orders to same driver.
CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_current_location(
    driver_location_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    current_location GEOGRAPHY(POINT, 4326), -- stores latitude and longitude of driver location
    is_available BOOLEAN, -- if driver is available to receive orders or not
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_location_pkey PRIMARY KEY (driver_location_id),
     CONSTRAINT driver_location_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE INDEX idx_driver_current_location
ON jippy_customer_and_order.driver_current_location USING GIST (current_location);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_attendance_logs (
    driver_attendance_log_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    status character varying(20) NOT NULL, -- online, offline
    changed_at timestamp without time zone NOT NULL,
    location GEOGRAPHY(POINT),   -- Where they were when they went online
    device_id TEXT,
    created_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT driver_attendance_logs_pkey PRIMARY KEY (driver_attendance_log_id),
     CONSTRAINT driver_attendance_logs_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_stats(
    driver_stats_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    work_date DATE DEFAULT CURRENT_DATE,
    first_online timestamp without time zone,
    last_offline timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_stats_pkey PRIMARY KEY (driver_stats_id),
     CONSTRAINT driver_stats_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

-- 2. Daily Summary for fast reporting
CREATE TABLE driver_daily_stats (
    driver_id INTEGER,
    work_date DATE DEFAULT CURRENT_DATE,
    first_online TIMESTAMP WITH TIME ZONE,
    last_offline TIMESTAMP WITH TIME ZONE,
    total_minutes_online INTEGER DEFAULT 0,
    PRIMARY KEY (driver_id, work_date)
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.reason_settings(
    reason_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    application_type character varying(50) NOT NULL, -- driver, outlet, customer
    reason_type character varying(50) NOT NULL, -- incentives hold, order cancellation,
    reason_text TEXT NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT reason_settings_pkey PRIMARY KEY (reason_id),
    CONSTRAINT reason_type UNIQUE (reason_type)
);


--- wallet system
-- companies point (ex: direct give 1750 points to customer- on every order 10% points can re redeemed)
--  referral points (ex: refer a friend and get 1000 points - on every order 10% points can re redeemed, refereed customer should place the order then only points will get)
-- daily streaks( daily login can be tracked, 25 points per day up to 30 days continuously, if it has a break in the middle, do it as 0 and start from first)
-- deals


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.referrals(
    referral_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    referrer_customer_id integer NOT NULL,
    referee_customer_id integer NOT NULL,
    referral_code character varying(20) NOT NULL,
    referral_status character varying(20) NOT NULL DEFAULT 'PENDING', -- pending, qualified,rewarded
    referral_type character varying(50) NOT NULL, -- customer,driver.
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT referral_program_pkey PRIMARY KEY (referral_id),
    CONSTRAINT referral_program_referrer_fk_key FOREIGN KEY (referrer_customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
     CONSTRAINT referral_program_referee_fk_key FOREIGN KEY (referee_customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.wallet_settings(
    wallet_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    points_type character varying(100), -- new Customer,referral,streak
    num_of_points integer, -- 200,150,25
    streak_min_days integer,--15
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT wallet_settings_pkey PRIMARY KEY (wallet_settings_id)
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_wallet_transactions(
    customer_wallet_transactions_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    wallet_id integer,
    points_type character varying(100), -- new Customer,referral,streak points
    points integer,
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_wallet_transactions_pkey PRIMARY KEY (customer_wallet_transactions_id),
    CONSTRAINT customer_wallet_transactions_customer_fk_key FOREIGN KEY (wallet_id)
                REFERENCES jippy_customer_and_order.customer_wallet (wallet_id)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION

);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.meal_subscription(
    meal_subscription_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    outlet_id integer NOT NULL,
    meal_preference character varying(100) NOT NULL, -- breakfast,lunch,dinner
    subscription_start_date timestamp without time zone NOT NULL, -- 22nd
    subscription_end_date timestamp without time zone NOT NULL, -- 25th
    subscription_status character varying(20) NOT NULL, -- active, cancelled, completed
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT meal_subscription_pkey PRIMARY KEY (meal_subscription_id)
);




CREATE TABLE IF NOT EXISTS jippy_customer_and_order.order_customizations(
   order_customizations_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   order_item_id integer NOT NULL, -- need to discuss about this, whether we need to store orderId or orderItemId
   less_oil BOOLEAN DEFAULT FALSE,
   less_spicy BOOLEAN DEFAULT FALSE,
   no_onion BOOLEAN DEFAULT FALSE,
   no_garlic BOOLEAN DEFAULT FALSE,
   extra_instructions TEXT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT order_customizations_pkey PRIMARY KEY (order_customizations_id),
    CONSTRAINT order_customizations_order_item_fk_key FOREIGN KEY (order_item_id)
            REFERENCES jippy_customer_and_order.order_items (order_item_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.order_waiting_period(
    order_waiting_period_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_rejection_id integer NOT NULL,
    allows_rejection boolean DEFAULT false,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT order_waiting_period_pkey PRIMARY KEY (order_waiting_period_id),
    CONSTRAINT order_waiting_rejection_fk_key FOREIGN KEY (order_rejection_id)
            REFERENCES jippy_customer_and_order.order_rejection (order_rejection_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
    );

 ALTER TABLE "jippy_customer_and_order"."driver_orders"
ADD COLUMN delivery_route GEOMETRY(LineStringM, 4326);

CREATE TABLE jippy_customer_and_order.group_orders_invitation (
    group_orders_invitation_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    host_customer_id INTEGER,
    outlet_id INTEGER NOT NULL,
    invitation_code character varying(10) UNIQUE, -- e.g., "GRP-X7Y2"
    status character varying(20) NOT NULL, -- CREATED, ACTIVE, COMPLETED, EXPIRED
    order_closing_time_in_minutes TIMESTAMP WITHOUT TIME ZONE NOT NULL, -- Host creation time + 30 mins
    payment_responsibility character varying(20) NOT NULL, -- 'HOST' or 'INDIVIDUAL'
    max_members INTEGER NOT NULL DEFAULT 10, -- Max members allowed in a group order
    order_type character varying(30) NOT NULl,
    community_event_id integer, -- used in case of community events for community order
    community_id integer, -- used in case of community group order
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by INTEGER,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by INTEGER,
    CONSTRAINT group_orders_invitation_pkey PRIMARY KEY (group_orders_invitation_id),
    CONSTRAINT group_order_customer_fkey FOREIGN KEY (host_customer_id)
        REFERENCES jippy_customer_and_order.customer (customer_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE jippy_customer_and_order.group_order_members (
    group_order_members_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    group_orders_invitation_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    delivery_address_id INTEGER NOT NULL, -- Crucial for your multi-address logic
    order_placed BOOLEAN DEFAULT FALSE, -- Tracks if this member has submitted their food choices
    is_dropped BOOLEAN DEFAULT FALSE, -- If the host removes a member or if they leave voluntarily
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by INTEGER,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by INTEGER,
    CONSTRAINT group_order_members_pkey PRIMARY KEY (group_order_members_id),
    CONSTRAINT group_order_members_fkey FOREIGN KEY (group_orders_invitation_id)
        REFERENCES jippy_customer_and_order.group_orders_invitation (group_orders_invitation_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT group_order_members_customers_fkey FOREIGN KEY (customer_id)
        REFERENCES jippy_customer_and_order.customer (customer_id)
         ON UPDATE NO ACTION
         ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.group_cart_items (
    group_cart_item_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    group_orders_invitation_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    merchant_unit_price NUMERIC(10, 2) NOT NULL,
    online_unit_price NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by INTEGER,
    updated_by INTEGER,

    CONSTRAINT group_cart_items_pkey PRIMARY KEY (group_cart_item_id),

    -- Foreign key to your group session table
    CONSTRAINT fk_gci_group_order FOREIGN KEY (group_orders_invitation_id)
        REFERENCES jippy_customer_and_order.group_orders_invitation (group_orders_invitation_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    -- Foreign key to ensure it's a valid customer adding items
    CONSTRAINT fk_gci_customer FOREIGN KEY (customer_id)
        REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE INDEX idx_group_cart_session ON jippy_customer_and_order.group_cart_items (group_orders_id);

CREATE TABLE jippy_customer_and_order.group_order_price_breakup (
    group_order_price_breakup_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    group_orders_invitation_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    order_amount NUMERIC(10, 2) NOT NULL,
    deliver_charges NUMERIC(10, 2) NOT NULL,
    surge_fee NUMERIC(10, 2) NOT NULL,
    packaging_fee NUMERIC(10, 2) NOT NULL,
    gst NUMERIC(10, 2) NOT NULL,
    platform_fee NUMERIC(10,2) NOT NULL,
    order_total_amount NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT group_order_price_breakup_pkey PRIMARY KEY (group_order_price_breakup_id),
    CONSTRAINT group_order_price_breakup_fkey FOREIGN KEY (group_orders_invitation_id)
        REFERENCES jippy_customer_and_order.group_orders_invitation (group_orders_invitation_id)
         ON UPDATE NO ACTION
         ON DELETE NO ACTION
);

CREATE TABLE jippy_customer_and_order.group_order_payments (
    group_order_payment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    group_orders_invitation_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    amount_to_pay NUMERIC(10,2) NOT NULL,
    payment_status VARCHAR(20) NOT NULL, -- PENDING, PAID, FAILED
    payment_transaction_id VARCHAR(100),
    CONSTRAINT group_order_payments_pkey PRIMARY KEY (group_order_payment_id),
    CONSTRAINT group_order_payments_fkey FOREIGN KEY (group_orders_invitation_id)
        REFERENCES jippy_customer_and_order.group_orders_invitation (group_orders_invitation_id)
         ON UPDATE NO ACTION
         ON DELETE NO ACTION
);


CREATE TABLE jippy_customer_and_order.customer_otp
(
    customer_otp_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL,
    otp_hash VARCHAR(255) NOT NULL,
    otp_reference_id VARCHAR(100),
    retry_count INTEGER NOT NULL DEFAULT 0,
    resend_count INTEGER NOT NULL DEFAULT 0,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER,
    updated_at timestamp without time zone,
    updated_by INTEGER,
    CONSTRAINT customer_otp_pkey PRIMARY KEY (customer_otp_id),
    CONSTRAINT fk_customer_otp_customer
        FOREIGN KEY (customer_id)
        REFERENCES jippy_customer_and_order.customer(customer_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE jippy_customer_and_order.customer_communities (
    customer_communities_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    community_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    created_by integer,
    updated_at timestamp without time zone NOT NULL,
    updated_by integer
   CONSTRAINT customer_communities_pkey PRIMARY KEY (customer_communities_id),
   CONSTRAINT customer_communities_unique UNIQUE(customer_id, community_id)
       CONSTRAINT customer_communities_fkey FOREIGN KEY (customer_id)
           REFERENCES jippy_customer_and_order.customer(customer_id)
           ON UPDATE NO ACTION
           ON DELETE NO ACTION
);

CREATE TABLE jippy_customer_and_order.community (
    community_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    community_name character varying(100) NOT NULL,
    community_boundary GEOGRAPHY(POLYGON, 4326) NOT NULL,
    community_area_id integer NOT NULL,
    about_community TEXT,
    established_year character varying(20),
    community_image_url character varying(100),
	created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT communities_pkey PRIMARY KEY (community_id)
);
CREATE INDEX community_boundary_idx ON jippy_customer_and_order.community USING GIST (community_boundary);

CREATE TABLE jippy_customer_and_order.community_events (
    community_events_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    community_id integer NOT NULL,
    event_title character varying(100) NOT NULL,            -- e.g., 'Community Potluck'
    event_description TEXT,                       -- e.g., 'Bring a dish, share happiness!'
    image_url  character varying(512),                 -- URL for the event cover illustration
    outlet_id integer NOT NULL,
    max_members integer NOT NULL,
    -- Date & Time
    delivery_time timestamp without time zone NOT NULL, -- Handles both Date & Time (e.g., 2026-05-25 6:00:00)
	event_start_date timestamp without time zone NOT NULL,
	event_end_date timestamp without time zone NOT NULL,
	booking_start_date timestamp without time zone NOT NULL,
	booking_end_date timestamp without time zone NOT NULL,
    -- Location (Two ways to handle this)
    location_name character varying(100) NOT NULL,    -- e.g., 'At Club House' or 'At Park Area'
    created_at timestamp without time zone NOT NULL,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT community_events_pkey PRIMARY KEY (community_events_id)
);

CREATE TABLE jippy_customer_and_order.event_members (
    event_members_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    community_event_id integer NOT NULL,
    customer_id integer NOT NULL,
    status VARCHAR(50) NOT NULL, -- 'going', 'interested', 'maybe'
    created_at timestamp without time zone NOT NULL,
    created_by integer,
   CONSTRAINT event_members_pkey PRIMARY KEY (event_members_id),
   CONSTRAINT event_members_event_fkey FOREIGN KEY (community_event_id)
              REFERENCES jippy_customer_and_order.community_events(community_event_id)
              ON UPDATE NO ACTION
              ON DELETE NO ACTION
);



