package com.jippy.foodandmart.dto;

import lombok.*;

import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FmBulkOutletResultDTO {

    /**
     * Total number of rows received from the bulk file.
     */
    private int totalRows;

    /**
     * Number of outlets successfully created.
     */
    private int successCount;

    /**
     * Number of rows that failed during processing.
     */
    private int failureCount;

    /**
     * Login credentials for successfully created outlets.
     * <p>
     * Username/password are included here because they may be
     * automatically generated by the backend when they are not
     * provided in the Excel/CSV file.
     */
    private List<OutletCredential> credentials;

    /**
     * Details of rows that could not be processed.
     */
    private List<OutletError> errors;


    // ============================================================
    // SUCCESSFUL OUTLET CREDENTIALS
    // ============================================================

    /**
     * Credential entry for each successfully created outlet.
     */
    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class OutletCredential {

        /**
         * Newly created outlet ID.
         */
        private Integer outletId;

        /**
         * Newly created outlet name.
         */
        private String outletName;

        /**
         * Outlet login username.
         * <p>
         * This will contain either:
         * - Username provided in Excel/CSV
         * - Automatically generated username
         */
        private String outletLoginId;

        /**
         * Outlet login password.
         * <p>
         * This will contain either:
         * - Password provided in Excel/CSV
         * - Automatically generated password
         */
        private String outletPassword;
    }


    // ============================================================
    // FAILED OUTLET ROW
    // ============================================================

    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class OutletError {

        /**
         * Excel/CSV row number.
         */
        private int rowNumber;

        /**
         * Outlet name from the failed row.
         */
        private String outletName;

        /**
         * Reason why the row failed.
         */
        private String reason;
    }
}