package com.jippy.foodandmart.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.*;

@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FmMerchantRequestDTO {

    // ============================================================
    // VALIDATION GROUPS
    // ============================================================

    /**
     * Validation group for normal/single merchant creation.
     * <p>
     * Email, username and password are mandatory in this flow.
     */
    public interface SingleMerchantValidation {
    }

    /**
     * Validation group for bulk merchant upload.
     * <p>
     * Email, username and password are optional in this flow.
     * Username/password are generated by the bulk service when blank.
     */
    public interface BulkMerchantValidation {
    }

    // ============================================================
    // BASIC MERCHANT DETAILS
    // ============================================================

    @Schema(description = "Merchant's first name", example = "Rohan")
    @NotBlank(message = "First name is required")
    @Size(min = 2, max = 75, message = "First name must be between 2 and 75 characters")
    @Pattern(regexp = "^[A-Za-z ]+$", message = "First name must contain only letters")
    private String firstName;


    @Schema(description = "Merchant's last name", example = "Vadluri")
    @NotBlank(message = "Last name is required")
    @Size(min = 2, max = 75, message = "Last name must be between 2 and 75 characters")
    @Pattern(regexp = "^[A-Za-z ]+$", message = "Last name must contain only letters")
    private String lastName;

    // ============================================================
    // EMAIL
    // ============================================================

    @Schema(description = "Merchant's email address. Required for single creation and optional for bulk upload.", example = "rohan@gmail.com")
    @NotBlank(groups = SingleMerchantValidation.class, message = "Email is required")
    @Email(message = "Invalid email format")
    @Size(max = 150, message = "Email must not exceed 150 characters")
    private String email;

    // ============================================================
    // PHONE
    // ============================================================

    @Schema(description = "Merchant's mobile number", example = "9876543210")
    @NotBlank(message = "Phone number is required")
    @Pattern(regexp = "^[6-9]\\d{9}$", message = "Phone must be a valid 10-digit Indian mobile number")
    private String phone;

    // ============================================================
    // USERNAME
    // ============================================================

    @Schema(description = "Merchant portal username. Required for single creation; optional for bulk upload.", example = "rohan123")
    @NotBlank(groups = SingleMerchantValidation.class, message = "Username is required")
    @Size(min = 4, max = 50, message = "Username must be between 4 and 50 characters")
    private String username;

    // ============================================================
    // PASSWORD
    // ============================================================

    @Schema(description = "Merchant portal password. Required for single creation; optional for bulk upload.", example = "Rohan@123")
    @NotBlank(groups = SingleMerchantValidation.class, message = "Password is required")
    @Pattern(regexp = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=!]).{8,20}$", message = "Password must contain uppercase, lowercase, number and special character")
    private String password;

    // ============================================================
    // BUSINESS DETAILS
    // ============================================================

    private String outletType;

    private String uploadedBy;

    // ============================================================
    // KYC DETAILS
    // ============================================================


    private String pan;


    private String adhar;

    // ============================================================
    // BANK DETAILS
    // ============================================================


    private String accountNumber;


    private String ifscCode;


    private String bankLocation;

    private String nameInBankAccount;

    // ============================================================
    // DATE OF BIRTH
    // ============================================================


    private String dob;

    // ============================================================
    // FSSAI
    // ============================================================

//    @Schema(description = "FSSAI license number", example = "12345678901234")
//    @Pattern(regexp = "^\\d{14}$", message = "FSSAI must be a 14-digit number")
//    private String fssai;
//
//    // ============================================================
//    // GST
//    // ============================================================
//
//    @Schema(description = "GST Identification Number (GSTIN)", example = "36ABCDE1234F1Z5")
//    @Pattern(regexp = "^$|^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$", message = "GST must be a valid 15-character GSTIN")
//    private String gstNumber;

    // ============================================================
    // MERCHANT ADDRESS
    //
    // CSV / Excel provides names:
    //
    // State = Telangana
    // City  = Hyderabad
    // Area  = Kukatpally
    //
    // Service resolves:
    //
    // Telangana  -> stateId
    // Hyderabad  -> cityId
    // Kukatpally -> areaId
    // ============================================================

    private String buildingNumber;

    private String road;

    private String landmark;

//    =====================================================================================
//    ============== For MOBILE DropDowns For SINGLE CREATE - DROPDOWN IDs ================
    // ====================================================================================
    // SINGLE MERCHANT ADDRESS IDs
    // Used by dropdowns in single merchant creation
    // ============================================================

    @Schema(description = "State ID selected from dropdown", example = "36")
    private Integer stateId;

    @Schema(description = "City ID selected from dropdown", example = "101")
    private Integer cityId;

    @Schema(description = "Area ID selected from dropdown", example = "1001")
    private Integer areaId;


    // ============================================================
    // BULK UPLOAD - NAMES
    // ============================================================
    @Schema(description = "State name from CSV/Excel", example = "Telangana")
    @Size(max = 100, message = "State name must not exceed 100 characters")
    private String stateName;


    @Schema(description = "City name from CSV/Excel", example = "Hyderabad")
    @Size(max = 100, message = "City name must not exceed 100 characters")
    private String cityName;


    @Schema(description = "Area name from CSV/Excel", example = "Kukatpally")
    @Size(max = 100, message = "Area name must not exceed 100 characters")
    private String areaName;

    // ============================================================
    // LOCATION
    // ============================================================

    @Schema(description = "Merchant latitude", example = "17.4948")
    private String latitude;


    @Schema(description = "Merchant longitude", example = "78.3996")
    private String longitude;
}