package com.jippy.customerandorder.dto;

import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * Contains settlement calculation details for a single outlet.
 *
 * This DTO is used by the Customer and Order (CO) microservice
 * to send outlet-wise settlement amounts to the Food and Mart (FM)
 * microservice.
 *
 * CO is responsible for calculating the order-related amounts.
 * FM will use the outlet ID to check GST applicability from the
 * FM outlets table.
 */
@Getter
@Setter
public class CoOutletSettlementDto {

    /**
     * Outlet ID for which the settlement amount is calculated.
     *
     * This ID is received from the delivered orders.
     */
    private Integer outletId;

    /**
     * Total merchant amount generated by this outlet
     * from delivered orders during the selected settlement period.
     */
    private BigDecimal merchantTotalPrice;

    /**
     * Total merchant promotion amount deducted from
     * the delivered orders of this outlet.
     *
     * This is calculated from order_price_breakup.discount
     * where discount_type = 'MERCHANT_PROMOTION'.
     */
    private BigDecimal promotionDeductedAmount;
}