package com.jippy.division.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class PaymentVerifyRequestDto {

    //razor pay fields
    private String rzpOrderId;
    // 2. The explicit payment voucher ID generated by Razorpay upon successful capture (e.g., "pay_P9a8B7c6D5e4F")
    private String rzpPaymentId;
    // 3. The unique cryptographic hash sent by Razorpay to prove the payment was authentic (e.g., "9a8b7c6d5e...")
    private String rzpSignature;

    private String applicationOrderId;
    private String paymentMode;       // Razorpay,  PayU

    private String payuPaymentId;        // mihpayid -- generated by PayU servers after processing the
    // transaction maps to gateway payment id in db

    private String payuStatus;           // "success" / "failure"
    private String payuHash;             // Received hash from PayU
    private String amount;
    private String bankRefNum;
    private Integer customerId;

}
