server:
    port: 8081

spring:
  application:
    name: division


  #     gMail SMTP Configuration -- gmail integration
  mail:
    host: smtp.gmail.com
    port: 587
    username: jippyfooddelivery2026@gmail.com
    password: cgbh eipp hner gdap

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # --------------------------------------------------------

  datasource:
    URL: jdbc:postgresql://187.127.156.147:5432/div_db
    USERNAME: div_user
    PASSWORD: div_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
     hibernate:
      default_schema: jippy_division
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-admin:eureka-admin123@localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    # Forces the microservice to expose its docs at /api/fm/v3/api-docs
    path: /api/div/v3/api-docs

razorpay:
  key-id: ${RAZOR_KEY_ID}
  key-secret: ${RAZOR_KEY_SECRET}
  webhook-secret: YourWebhookSecretHere

paytm:
  mid: ${PAYTM_MID}
  merchantKey: ${PAYTM_MERCHANT_KEY}
  website: "DEFAULT"
  channel-id: "WAP"
  industry-type: "Retail"
  initiate-txn-url: "https://securestage.paytmpayments.com/theia/api/v1/initiateTransaction?mid="
  #initiate_txn_url: "https://securestage.paytmpayments.com/theia/api/v1/initiateTransaction?mid="
  callback-url: "https://securestage.paytmpayments.co/api/div/payment/callback/{orderId}"
  refund-url: "https://securegw-stage.paytm.in/refund/api/v1/asyncRefund"
  refund-status-url: "https://securegw-stage.paytm.in/v2/refund/status"

