CREATE SCHEMA IF NOT EXISTS jippy_division;

CREATE TABLE IF NOT EXISTS jippy_division.price_model
(
    price_model_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    price_model_name character varying(20),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT price_model_pkey PRIMARY KEY (price_model_id)
);

CREATE TABLE IF NOT EXISTS jippy_division.application_type
(
    application_type_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    application_name character varying(20),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT application_type_pkey PRIMARY KEY (application_type_id)
);

-- flat,percentage,birthday, happyHours,autocoupon,firstTimeLogin



CREATE TABLE IF NOT EXISTS jippy_division.coupons (
   coupon_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   coupon_code character varying(100)  NOT NULL,
   price_model_id integer,
   application_type integer,
   min_order_value NUMERIC(10,2),
   discount_value NUMERIC(10,2),
   payment_method integer,
   usage_limit_per_user integer,
   is_active BOOLEAN DEFAULT FALSE,
   start_time timestamp without time zone,
   end_time timestamp without time zone,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT coupons_pkey PRIMARY KEY (coupon_id),
    CONSTRAINT coupons_price_model_fk_key FOREIGN KEY (price_model_id)
            REFERENCES jippy_division.price_model (price_model_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_division.promotion_date(
promotion_date_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
promotion_from_date timestamp without time zone,
promotion_to_date timestamp without time zone,
no_of_slots integer,
created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT promotion_date_pkey PRIMARY KEY (promotion_date_id)
); 1 20 27 3

 CREATE TABLE IF NOT EXISTS jippy_division.promotion_time(
 promotion_time_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 slot_number integer,
 promotion_from_time timestamp without time zone,
 promotion_to_time timestamp without time zone,
 promotion_date_id integer,
 created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
     CONSTRAINT promotion_time_pkey PRIMARY KEY (promotion_time_id)
 ); 1 1 8 11 1
 2 2 12 14 1
 3 3 18 21 1

CREATE TABLE IF NOT EXISTS jippy_division.coupon_mapping_outlets_products (
   coupon_mapping_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   coupon_id integer  NOT NULL,
   outlet_id integer NOT NULL,
   product_id integer,
   area_id integer NOT NULL,
   promotion_date_id integer,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT coupon_mapping_pkey PRIMARY KEY (coupon_mapping_id),
    CONSTRAINT coupon_mapping_coupons_fk_key FOREIGN KEY (coupon_id)
            REFERENCES jippy_division.coupons (coupon_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);
 1 c1 o1 p1 a1 1
 2 c1 o1 p3 a1 1

CREATE TABLE IF NOT EXISTS jippy_division.price_drop_mapping_outlets_products (
   price_drop_mapping_outlets_products_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   price_drop_value NUMERIC(10,2)  NOT NULL,
   outlet_id integer NOT NULL,
   product_id integer NOT NULL,
   area_id integer NOT NULL,
   promotion_time_id integer,
   price_model_id integer,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT price_drop_mapping_outlets_products_pkey PRIMARY KEY (price_drop_mapping_outlets_products_id)
);

CREATE TABLE IF NOT EXISTS jippy_division.driver_settlement(
    settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    settlement_amount NUMERIC(10, 2) NOT NULL,
    settlement_status character varying(100), -- pending, completed, failed
    settlement_from_date timestamp without time zone,
    settlement_to_date timestamp without time zone,
    reason TEXT,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_settlement_pkey PRIMARY KEY (settlement_id)
);


CREATE TABLE IF NOT EXISTS jippy_division.driver_incentives_settlement(
    settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    incentives_amount NUMERIC(10, 2) NOT NULL,
    settlement_date timestamp without time zone,
    settlement_status character varying(100), -- pending, completed, failed
    reason TEXT,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_incentives_settlement_pkey PRIMARY KEY (settlement_id)
);


CREATE TABLE IF NOT EXISTS jippy_division.outlet_weekly_settlement(
    weekly_settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    week_start_date date NOT NULL,
    week_end_date date NOT NULL,
    total_settlement_amount NUMERIC(10, 2) NOT NULL,
    payment_status character varying(20) NOT NULL, -- pending, completed, payment_failed
    transaction_id character varying(100) NOT NULL,
    outlet_mobile_number character varying(15) NOT NULL,
    outlet_email character varying(100) NOT NULL,
    orders_count integer NOT NULL,
    deductions NUMERIC(10, 2),
    gst NUMERIC(10, 2),
    promotion_amount NUMERIC(10, 2),
    subscription_amount NUMERIC(10, 2),
    net_settlement_amount NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_weekly_settlement_pkey PRIMARY KEY (weekly_settlement_id)
);


CREATE TABLE IF NOT EXISTS jippy_division.email_templates(
    template_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    template_name character varying(100) NOT NULL, -- outlet settlement, driver settlement, incentives settlement,
    subject character varying(500) NOT NULL,--outlet settlement success
    body text NOT NULL,--
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT email_templates_pkey PRIMARY KEY (template_id)
);


INSERT INTO jippy_division.price_model(
	price_model_id, price_model_name, created_at, created_by)
	VALUES (1, 'FLAT', now(), 1);
INSERT INTO jippy_division.price_model(
	price_model_id, price_model_name, created_at, created_by)
	VALUES (2, 'PERCENTAGE', now(), 1);
