CREATE SCHEMA IF NOT EXISTS jippy_division;

CREATE TABLE IF NOT EXISTS jippy_division.price_model
(
    price_model_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    price_model_name character varying(20),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT price_model_pkey PRIMARY KEY (price_model_id)
);

CREATE TABLE IF NOT EXISTS jippy_division.application_type
(
    application_type_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    application_name character varying(20),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT application_type_pkey PRIMARY KEY (application_type_id)
);

-- flat,percentage,birthday, happyHours,autocoupon,firstTimeLogin



CREATE TABLE IF NOT EXISTS jippy_division.coupons (
   coupon_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   coupon_code character varying(100)  NOT NULL,
   price_model_id integer,
   application_type integer,
   min_order_value NUMERIC(10,2),
   discount_value NUMERIC(10,2),
   payment_method integer,
   usage_limit_per_user integer,
   is_active BOOLEAN DEFAULT FALSE,
   start_time timestamp without time zone,
   end_time timestamp without time zone,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT coupons_pkey PRIMARY KEY (coupon_id),
    CONSTRAINT coupons_price_model_fk_key FOREIGN KEY (price_model_id)
            REFERENCES jippy_division.price_model (price_model_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_division.promotion_date(
promotion_date_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
promotion_from_date timestamp without time zone,
promotion_to_date timestamp without time zone,
meal_time_slot_id integer,
created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT promotion_date_pkey PRIMARY KEY (promotion_date_id)
);

CREATE TABLE IF NOT EXISTS jippy_division.coupon_mapping_outlets_products (
   coupon_mapping_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   coupon_id integer  NOT NULL,
   outlet_id integer NOT NULL,
   product_id integer,
   location_type character varying(20) NOT NULL, -- outlet, area
   location_id integer NOT NULL, -- outlet_id or area_id based on location_type
   promotion_date_id integer,
   max_selection integer NOT NULL DEFAULT -1, --means unlimited
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT coupon_mapping_pkey PRIMARY KEY (coupon_mapping_id),
    CONSTRAINT coupon_mapping_coupons_fk_key FOREIGN KEY (coupon_id)
            REFERENCES jippy_division.coupons (coupon_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_division.price_drop_mapping_outlets_products (
   price_drop_mapping_outlets_products_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   price_drop_value NUMERIC(10,2)  NOT NULL,
   outlet_id integer NOT NULL,
   product_id integer NOT NULL,
   location_type character varying(20) NOT NULL, -- outlet, area
   location_id integer NOT NULL, -- outlet_id or area_id based on location_type
   area_id integer NOT NULL,
   promotion_date_id integer,
   price_model_id integer,
   max_selection integer NOT NULL DEFAULT -1, --means unlimited
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT price_drop_mapping_outlets_products_pkey PRIMARY KEY (price_drop_mapping_outlets_products_id)
);

CREATE TABLE IF NOT EXISTS jippy_division.driver_settlement(
    settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    settlement_amount NUMERIC(10, 2) NOT NULL,
    settlement_status character varying(100), -- pending, completed, failed
    settlement_from_date timestamp without time zone,
    settlement_to_date timestamp without time zone,
    reason TEXT,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_settlement_pkey PRIMARY KEY (settlement_id)
);


CREATE TABLE IF NOT EXISTS jippy_division.driver_incentives_settlement(
    settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    incentives_amount NUMERIC(10, 2) NOT NULL,
    settlement_date timestamp without time zone,
    settlement_status character varying(100), -- pending, completed, failed
    reason TEXT,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_incentives_settlement_pkey PRIMARY KEY (settlement_id)
);


CREATE TABLE IF NOT EXISTS jippy_division.outlet_weekly_settlement(
    weekly_settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    week_start_date date NOT NULL,
    week_end_date date NOT NULL,
    total_settlement_amount NUMERIC(10, 2) NOT NULL,
    payment_status character varying(20) NOT NULL, -- pending, completed, payment_failed
    transaction_id character varying(100) NOT NULL,
    outlet_mobile_number character varying(15) NOT NULL,
    outlet_email character varying(100) NOT NULL,
    orders_count integer NOT NULL,
    deductions NUMERIC(10, 2),
    gst NUMERIC(10, 2),
    promotion_amount NUMERIC(10, 2),
    subscription_amount NUMERIC(10, 2),
    net_settlement_amount NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_weekly_settlement_pkey PRIMARY KEY (weekly_settlement_id)
);


CREATE TABLE IF NOT EXISTS jippy_division.email_templates(
    template_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    template_name character varying(100) NOT NULL, -- outlet settlement, driver settlement, incentives settlement,
    subject character varying(500) NOT NULL,--outlet settlement success
    body text NOT NULL,--
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT email_templates_pkey PRIMARY KEY (template_id)
);

CREATE TABLE IF NOT EXISTS jippy_division.payment_transactions (
    payment_transactions_id UUID NOT NULL DEFAULT gen_random_uuid(),
    application_order_id CHARACTER VARYING(30) NOT NULL,
    payment_method_type CHARACTER VARYING(30) NOT NULL,        -- 'RAZORPAY', 'PAYTM', etc.

    -- Gateway Reference IDs (Must be nullable to support multi-gateway coexistence)
    gateway_order_id  CHARACTER VARYING(255),                             -- Holds Razorpay Order ID (Null for Paytm)
    gateway_payment_id  CHARACTER VARYING(255),                           -- Holds Razorpay Payment ID or Paytm TXNID
    gateway_signature  CHARACTER VARYING(512),                            -- Holds Razorpay Signature or Paytm CHECKSUMHASH

    payment_status  CHARACTER VARYING(50) DEFAULT 'PENDING',               -- PENDING, SUCCESS, FAILED, REFUNDED
    amount integer NOT NULL,                                        -- Stored in Paise/Lowest denomination (Integer)
    currency  CHARACTER VARYING(10) DEFAULT 'INR',

    -- Banking Reconciliation Data (Phase 3 Webhook)
    txn_rrn  CHARACTER VARYING(100),                                       -- Razorpay rrn / Paytm BANKTXNID
    bank_auth_code  CHARACTER VARYING(50),                                 -- Razorpay bank_auth_code / Paytm RESPCODE
    bank_name  CHARACTER VARYING(100),                                     -- e.g., 'HDFC', 'SBI', 'VALET'

    -- Metadata and Debugging Logs
    gateway_raw_response TEXT,                                  -- Stores raw JSON dump from webhooks for audit trails
    created_at timestamp without time zone,
    updated_at timestamp without time zone,

    CONSTRAINT payment_transactions_pkey PRIMARY KEY (payment_transactions_id)
);

-- Indexes for lightning-fast lookups during Webhooks
CREATE INDEX IF NOT EXISTS idx_payment_app_order ON jippy_division.payment_transactions(application_order_id);
CREATE INDEX IF NOT EXISTS idx_payment_gateway_pay_id ON jippy_division.payment_transactions(gateway_payment_id);


CREATE TABLE  jippy_division.refund_transactions(
    refund_transactions_id UUID NOT NULL DEFAULT gen_random_uuid(),
    application_order_id character varying(30) NOT NULL,
    payment_transactions_id UUID NOT NULL,
    gateway_refund_id character varying(100) UNIQUE,                    -- Returned by Razorpay API
    amount_in_paise integer NOT NULL,
    refund_status character varying(30) NOT NULL DEFAULT 'PENDING',
    reason TEXT NOT NULL,
    bank_arn character varying(30),
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT refund_transactions_pkey PRIMARY KEY (refund_transactions_id),
    CONSTRAINT fk_transaction FOREIGN KEY (payment_transactions_id)
        REFERENCES jippy_division.payment_transactions (payment_transactions_id)
        ON UPDATE NO ACTION
         ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_division.promotion_schedules (
    promotion_schedules_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    -- Metadata / Source tracing
    source_type VARCHAR(30) NOT NULL, -- 'COUPON', 'PRICE_DROP', 'RESTAURANT_PROMO'
    source_id INTEGER NOT NULL,       -- FK to primary key of mapping/plan table

    -- Location & Outlet Scope
    location_type VARCHAR(20) NOT NULL, -- 'OUTLET', 'AREA', 'CITY', 'STATE'
    location_id INTEGER NOT NULL,       -- ID corresponding to location_type
    outlet_id INTEGER,                  -- Optional: Specific outlet ID (if applicable)
    product_id INTEGER,                 -- Optional: NULL means applies to all products in scope

    -- Time Window
    start_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status character varying(50),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT promotion_schedules_pkey PRIMARY KEY (promotion_schedules_id)
);

INSERT INTO jippy_division.price_model(
	price_model_id, price_model_name, created_at, created_by)
	VALUES (1, 'FLAT', now(), 1);
INSERT INTO jippy_division.price_model(
	price_model_id, price_model_name, created_at, created_by)
	VALUES (2, 'PERCENTAGE', now(), 1);
