CREATE SCHEMA IF NOT EXISTS jippy_expenses;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. Expense Categories & Sub-Categories
CREATE TABLE jippy_expenses.expense_categories (
    expense_category_id  integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    expense_category_name character varying(100) NOT NULL UNIQUE,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT expense_category_pkey PRIMARY KEY (expense_category_id)
);

CREATE TABLE jippy_expenses.expense_sub_categories (
    expense_sub_category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    expense_category_id INTEGER NOT NULL
    sub_category_name character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT expense_sub_category_pkey PRIMARY KEY (expense_sub_category_id),
    CONSTRAINT expense_sub_category_category_fkey (expense_category_id)
    REFERENCES jippy_expenses.expense_categories(expense_category_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

-- 3. Projects & Cost Centers
CREATE TABLE jippy_expenses.projects (
    project_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_name character varying(100) NOT NULL UNIQUE,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT project_pkey PRIMARY KEY (project_id)
);



CREATE TABLE jippy_expenses.vendors (
    vendor_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    vendor_name character varying(150) NOT NULL,
    contact_person character varying(100),
    email character varying(150),
    phone_number character varying(20),
    tax_number character varying(50),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT vendor_pkey PRIMARY KEY (vendor_id)
);


CREATE TABLE jippy_expenses.stores_offices (
    store_office_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    store_office_name character varying(100) NOT NULL,
    location_type character varying(50) DEFAULT 'Office', -- e.g., 'Store', 'Branch', 'Head Office'
    address TEXT,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT store_office_pkey PRIMARY KEY (store_office_id)
);

CREATE TABLE jippy_expenses.paid_from_accounts (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_name character varying(100) NOT NULL, -- e.g., 'Corporate Bank Account', 'Petty Cash', 'Company Credit Card'
    account_number character varying(50),
    account_type character varying(50) NOT NULL, -- e.g., 'Bank Account', 'Credit Card', 'Petty Cash'
    currency character varying(10) DEFAULT 'INR',
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT paid_from_account_pkey PRIMARY KEY (account_id)
);

CREATE TABLE jippy_expenses.expenses (
    expenses_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_id integer NOT NULL,
    expense_category_id integer,
    expense_sub_category_id integer,
    project_id integer,
    vendor_id integer,
    store_office_id integer,
    paid_from_account_id integer,

    -- Expense Details
    expense_date DATE NOT NULL,
    expense_type character varying(50), -- day,weekly,monthly,quarterly,yearly
    description TEXT,
    currency character varying(10) DEFAULT 'INR',
    amount NUMERIC(12, 2) NOT NULL,
    payment_mode character varying(50),
    expense_type character varying(50), -- Reimbursable, company expenses

    -- GST Fields
    is_gst_applicable BOOLEAN DEFAULT FALSE,
    gst_number character varying(15),
    cgst_amount NUMERIC(12, 2) DEFAULT 0.00,
    sgst_amount NUMERIC(12, 2) DEFAULT 0.00,
    tax_amount NUMERIC(12, 2) DEFAULT 0.00,
    total_gst NUMERIC(12, 2) NOT NULL,

    -- TDS Fields
    is_tds_applicable BOOLEAN DEFAULT FALSE,
    tds_amount NUMERIC(12, 2) DEFAULT 0.00,
    net_payable_amount NUMERIC(12, 2),

    is_approved boolean default false,

    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,

    -- Primary Key
    CONSTRAINT expenses_pkey PRIMARY KEY (expense_id),

    -- Foreign Keys
    CONSTRAINT fk_expenses_category FOREIGN KEY (expense_category_id) REFERENCES jippy_expenses.expense_categories(expense_category_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_expenses_sub_category FOREIGN KEY (expense_sub_category_id) REFERENCES jippy_expenses.expense_sub_categories(expense_sub_category_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_expenses_project FOREIGN KEY (project_id) REFERENCES jippy_expenses.projects(project_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_expenses_vendor FOREIGN KEY (vendor_id) REFERENCES jippy_expenses.vendors(vendor_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_expenses_store_office FOREIGN KEY (store_office_id) REFERENCES jippy_expenses.stores_offices(store_office_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_expenses_paid_from_account FOREIGN KEY (paid_from_account_id) REFERENCES jippy_expenses.paid_from_accounts(account_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE jippy_expenses.expense_documents (
    expense_documents_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    document_name character varying(100) NOT NULL, -- e.g., 'Corporate Bank Account', 'Petty Cash', 'Company Credit Card'
    document_image_link character varying(500),
    expense_id integer NOT NULL, -- e.g., 'Bank Account', 'Credit Card', 'Petty Cash'
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT expense_documents_pkey PRIMARY KEY (expense_documents_id),
    CONSTRAINT expense_documents_expenses_fkey FOREIGN KEY (expense_id)
    REFERENCES jippy_expenses.expense_documents
    ON UPDATE NO ACTION ON DELETE NO ACTION
);
