server:
  port: 8086

spring:
  application:
    name: driver

    #     gMail SMTP Configuration -- gmail integration
  mail:
    host: smtp.gmail.com
    port: 587
    username: jippyfooddelivery2026@gmail.com
    password: cgbh eipp hner gdap

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# --------------------------------------------------------

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:postgresql://187.127.156.147:5435/driver_db
    username: driver_user
    password: driver_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
      ddl-auto: update
    show-sql: true


    #  Kafka Producer Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:187.127.156.147:9092}
    producer:
      # Serializes the Message Key (Order ID) as a String
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Serializes the OrderEvent object into a JSON string
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      # Ensures the message is acknowledged by Kafka brokers
      acks: all

    consumer:
      # Starts reading from the beginning of the topic if no offset is found
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # CRITICAL: Tell Spring which Java packages are safe to deserialize
        spring.json.trusted.packages: "com.jippy.driver.dto"


  #data:
   # redis:
    #  host: localhost
     # port: 6379
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-admin:eureka-admin123@localhost:8070/eureka/

springdoc:
  api-docs:
    # Forces the microservice to expose its docs at /api/fm/v3/api-docs
    path: /api/driver/v3/api-docs
  swagger-ui:
    path: /api/driver/swagger-ui.html

aws:
  s3:
    bucket-name: jippys3bucket
    region: ap-south-2
    access-key:
    secret-key: