CREATE TABLE IF NOT EXISTS jippy_driver.driver(
    driver_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    phone_number character varying(15) NOT NULL,
    email character varying(100),
    nominee_name character varying(50),
    nominee_phone_number character varying(15),
    is_nominee_verified BOOLEAN DEFAULT FALSE,
    family_member_name character varying(50),
    family_member_phone_number character varying(15),
    is_family_member_verified BOOLEAN DEFAULT FALSE,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_pkey PRIMARY KEY (driver_id)

);

CREATE TABLE IF NOT EXISTS jippy_driver.driver_kyc(
    driver_kyc_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    aadhar_number character varying(20) NOT NULL,
    driving_license_number character varying(20) NOT NULL,
    rc_copy character varying(100) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_kyc_pkey PRIMARY KEY (driver_kyc_id),
     CONSTRAINT driver_kyc_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_driver.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_driver.driver_delivery_charge_settings(
    delivery_charge_setting_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pick_up_kms_range_from NUMERIC(10,2) NOT NULL,
    pick_up_kms_range_to NUMERIC(10,2) NOT NULL,
    unit_price_per_pick_km NUMERIC(10, 2) NOT NULL,
    delivery_kms_range_from NUMERIC(10, 2) NOT NULL,
    delivery_kms_range_to NUMERIC(10, 2) NOT NULL,
    unit_price_per_deliver_km NUMERIC(10, 2) NOT NULL,
    --num_of_orders integer NOT NULL,
    -- incentives_amount NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_delivery_charge_settings_pkey PRIMARY KEY (delivery_charge_setting_id)
);

CREATE TABLE jippy_driver.zones (
    zone_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    zone_name character varying(100) NOT NULL,
    boundary GEOGRAPHY(POLYGON, 4326) NOT NULL,
    zone_type character varying(30) NOT NULL, --DRIVER-ZONE,COMMUNITY
	created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT zones_pkey PRIMARY KEY (zone_id)
);
CREATE INDEX boundary_idx ON jippy_driver.zones USING GIST (boundary);

CREATE TABLE IF NOT EXISTS jippy_driver.driver_incentive_settings(
    driver_incentive_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    orders_count integer NOT NULL,
    incentive_amount NUMERIC(10, 2) NOT NULL,
    zone_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_incentives_pkey PRIMARY KEY (driver_incentive_settings_id),
    CONSTRAINT driver_incentives_zone_fk_key FOREIGN KEY (zone_id)
                REFERENCES jippy_driver.zones (zone_id)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
);
--ALTER TABLE jippy_driver.driver_incentive_settings
--ADD CONSTRAINT uk_orders_count
--UNIQUE(orders_count);

CREATE TABLE if NOT EXISTS jippy_driver.driver_orders(
    driver_order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    order_id character varying(30) NOT NULL,
    pick_up_distance_in_kms NUMERIC(10,2),
    delivery_distance_in_kms NUMERIC(10,2),
    pick_up_charges NUMERIC(10,2),
    deliver_charges NUMERIC(10,2),
    total_delivery_fee NUMERIC(10, 2) NOT NULL, --100
    surge_fee NUMERIC(10,2), --20
    tips NUMERIC(10, 2), --10
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_order_id_pkey PRIMARY KEY (driver_order_id),
     CONSTRAINT driver_orders_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_driver.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);



CREATE TABLE IF NOT EXISTS jippy_driver.driver_zone_assignment(
    driver_zone_assignment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    zone_id integer NOT NULL,
    created_by integer,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT driver_zone_assignment_pkey PRIMARY KEY (driver_zone_assignment_id),
     CONSTRAINT driver_zone_assignment_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_driver.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);





-- Track driver attendence daily
-- Fleet manager can track driver history.
-- Driver can not deliver orders though they are available, then we have to stop incentives.
--Driver settlements can be done in weekly 2 times, but incentives are done monthly once.
CREATE TABLE IF NOT EXISTS jippy_driver.driver_history(
    driver_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    no_of_orders integer NOT NULL,
    last_login_date timestamp without time zone,
    available_from_time timestamp without time zone,
    available_to_time timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_history_pkey PRIMARY KEY (driver_history_id),
     CONSTRAINT driver_history_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_driver.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_driver.driver_wallet(
    driver_wallet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    total_cod_amount NUMERIC(10, 2) DEFAULT 1000,-- if cod amount >=1000 then driver will not receive orders, driver needs to pay taht 1000rs to company account. Fleet manager can release the orders lock.
    orders_lock BOOLEAN DEFAULT false,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_wallet_pkey PRIMARY KEY (driver_wallet_id),
     CONSTRAINT driver_wallet_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_driver.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);
--to prevent multiple wallet records for same driver
ALTER TABLE jippy_driver.driver_wallet
ADD CONSTRAINT unique_driver_wallet UNIQUE (driver_id);


CREATE TABLE IF NOT EXISTS jippy_driver.driver_wallet_transactions(
    driver_wallet_transactions_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_wallet_id integer NOT NULL,
    order_id character varying(30) NOT NULL,
    cod_amount NUMERIC(10,2) NOT NULL,
    -- transaction_type character varying(20) NOT NULL, -- credit or debit
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_wallet_transactions_pkey PRIMARY KEY (driver_wallet_transactions_id),
     CONSTRAINT driver_wallet_transactions_fk_key FOREIGN KEY (driver_wallet_id)
            REFERENCES jippy_driver.driver_wallet (driver_wallet_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

-- if same customere placed 2 orders within 3kms from different outlets, then can we assign 2 orders to same driver.
CREATE TABLE IF NOT EXISTS jippy_driver.driver_current_location(
    driver_location_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    current_location GEOGRAPHY(POINT, 4326), -- stores latitude and longitude of driver location
    is_available BOOLEAN, -- if driver is available to receive orders or not
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_location_pkey PRIMARY KEY (driver_location_id),
     CONSTRAINT driver_location_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_driver.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE INDEX idx_driver_current_location
ON jippy_driver.driver_current_location USING GIST (current_location);

CREATE TABLE IF NOT EXISTS jippy_driver.driver_attendance_logs (
    driver_attendance_log_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    status character varying(20) NOT NULL, -- online, offline
    changed_at timestamp without time zone NOT NULL,
    location GEOGRAPHY(POINT),   -- Where they were when they went online
    device_id TEXT,
    created_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT driver_attendance_logs_pkey PRIMARY KEY (driver_attendance_log_id),
     CONSTRAINT driver_attendance_logs_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_driver.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_driver.driver_stats(
    driver_stats_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    work_date DATE DEFAULT CURRENT_DATE,
    first_online timestamp without time zone,
    last_offline timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_stats_pkey PRIMARY KEY (driver_stats_id),
     CONSTRAINT driver_stats_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_driver.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_driver.driver_incentive_history(
    driver_incentive_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    curr_date DATE DEFAULT CURRENT_DATE,
    incentive_amount NUMERIC(10, 2) NOT NULL,
    completed_orders_count integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_incentive_history_pkey PRIMARY KEY (driver_incentive_history_id),
     CONSTRAINT driver_incentive_history_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_driver.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


ALTER TABLE "jippy_driver"."zones"
ALTER COLUMN boundary TYPE geography(MultiPolygon, 4326);