CREATE SCHEMA IF NOT EXISTS jippy_driver;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Base Drivers Table
CREATE TABLE IF NOT EXISTS jippy_driver.driver(
    driver_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    phone_number character varying(15) NOT NULL,
    email character varying(100),
    nominee_name character varying(50),
    nominee_phone_number character varying(15),
    is_nominee_verified BOOLEAN DEFAULT FALSE,
    family_member_name character varying(50),
    family_member_phone_number character varying(15),
    is_family_member_verified BOOLEAN DEFAULT FALSE,
    profile_pic_url character varying(500),
    is_approved boolean NOT NULL DEFAULT false,
    ready_to_accept_orders boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_pkey PRIMARY KEY (driver_id)
);

-- 2. Zones Table (Moved up so foreign keys can reference it)
CREATE TABLE IF NOT EXISTS jippy_driver.zones (
    zone_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    zone_name character varying(100) NOT NULL,
    boundary GEOGRAPHY(MultiPolygon, 4326) NOT NULL,
    status character varying(1) NOT NULL DEFAULT 'Y',
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT zones_pkey PRIMARY KEY (zone_id)
);

CREATE INDEX IF NOT EXISTS boundary_idx ON jippy_driver.zones USING GIST (boundary);

-- 3. Driver KYC Table
CREATE TABLE IF NOT EXISTS jippy_driver.driver_kyc(
    driver_kyc_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    aadhar_number character varying(20) NOT NULL,
    pan_number character varying (20) NOT NULL,
    driving_license_number character varying(20) NOT NULL,
    rc_copy character varying(100) NOT NULL,
    aadhar_number_url character varying(500),
    pan_number_url character varying(500),
    driving_license_number_url character varying(500),
    rc_copy_url character varying(500),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_kyc_pkey PRIMARY KEY (driver_kyc_id),
    CONSTRAINT driver_kyc_driver_fk_key FOREIGN KEY (driver_id)
        REFERENCES jippy_driver.driver (driver_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- 4. Delivery Charge Settings
CREATE TABLE IF NOT EXISTS jippy_driver.driver_delivery_charge_settings(
    delivery_charge_setting_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    kms_range_from NUMERIC(10,2) NOT NULL,
    kms_range_to NUMERIC(10,2) NOT NULL,
    unit_price_per_km NUMERIC(10,2) NOT NULL,
    charge_type CHARACTER VARYING(30) NOT NULL,
    delivery_type CHARACTER VARYING(30) NOT NULL,
    driver_type CHARACTER VARYING(30) NOT NULL,
    service_type CHARACTER VARYING(30) NOT NULL,
    vehicle_type CHARACTER VARYING(30) NOT NULL,
    fuel_type CHARACTER VARYING(30) NOT NULL,
    zone_id INTEGER NOT NULL,
    currency_code CHARACTER VARYING(30) NOT NULL,
    waiting_free_minutes INTEGER NOT NULL DEFAULT 5,
    waiting_per_minute NUMERIC(10,2) NOT NULL,
    night_charge NUMERIC(10,2) NOT NULL,
    peak_charge NUMERIC(10,2) NOT NULL,
    weather_surcharge NUMERIC(10,2) NOT NULL,
    remote_area_charge NUMERIC(10,2) NOT NULL,
    remote_zone_surcharge NUMERIC(10,2) NOT NULL,
    status CHARACTER VARYING(30) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by INTEGER,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by INTEGER,
    CONSTRAINT driver_delivery_charge_settings_pkey PRIMARY KEY (delivery_charge_setting_id),
    CONSTRAINT driver_zone_fk FOREIGN KEY (zone_id)
        REFERENCES jippy_driver.zones (zone_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- 5. Incentive Settings
CREATE TABLE IF NOT EXISTS jippy_driver.driver_incentive_settings(
    driver_incentive_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    orders_count integer NOT NULL,
    incentive_amount NUMERIC(10, 2) NOT NULL,
    zone_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_incentives_pkey PRIMARY KEY (driver_incentive_settings_id),
    CONSTRAINT driver_incentives_zone_fk_key FOREIGN KEY (zone_id)
        REFERENCES jippy_driver.zones (zone_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- 6. Driver Orders Table
CREATE TABLE IF NOT EXISTS jippy_driver.driver_orders(
    driver_order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    order_id character varying(30) NOT NULL,
    pick_up_distance_in_kms NUMERIC(10,2),
    delivery_distance_in_kms NUMERIC(10,2),
    pick_up_charges NUMERIC(10,2),
    deliver_charges NUMERIC(10,2),
    total_delivery_fee NUMERIC(10, 2) NOT NULL,
    surge_fee NUMERIC(10,2),
    tips NUMERIC(10, 2),
    delivery_route GEOMETRY(LineStringM, 4326),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_order_id_pkey PRIMARY KEY (driver_order_id),
    CONSTRAINT driver_orders_driver_fk_key FOREIGN KEY (driver_id)
        REFERENCES jippy_driver.driver (driver_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS idx_driver_order_delivery_route
ON jippy_driver.driver_orders USING GIST (delivery_route);

-- 7. Driver Zone Assignment
CREATE TABLE IF NOT EXISTS jippy_driver.driver_zone_assignment(
    driver_zone_assignment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    zone_id integer NOT NULL,
    created_by integer,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT driver_zone_assignment_pkey PRIMARY KEY (driver_zone_assignment_id),
    CONSTRAINT driver_zone_assignment_driver_fk_key FOREIGN KEY (driver_id)
        REFERENCES jippy_driver.driver (driver_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT driver_zone_assignment_zone_fk_key FOREIGN KEY (zone_id)
        REFERENCES jippy_driver.zones (zone_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT unique_driver_zone UNIQUE (driver_id, zone_id)
);

-- 8. Driver History
CREATE TABLE IF NOT EXISTS jippy_driver.driver_history(
    driver_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    no_of_orders integer NOT NULL,
    last_login_date timestamp without time zone,
    available_from_time timestamp without time zone,
    available_to_time timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_history_pkey PRIMARY KEY (driver_history_id),
    CONSTRAINT driver_history_driver_fk_key FOREIGN KEY (driver_id)
        REFERENCES jippy_driver.driver (driver_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- 9. Driver Wallet
CREATE TABLE IF NOT EXISTS jippy_driver.driver_wallet(
    driver_wallet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    total_cod_amount NUMERIC(10, 2) DEFAULT 1000,
    orders_lock BOOLEAN DEFAULT false,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_wallet_pkey PRIMARY KEY (driver_wallet_id),
    CONSTRAINT driver_wallet_driver_fk_key FOREIGN KEY (driver_id)
        REFERENCES jippy_driver.driver (driver_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT unique_driver_wallet UNIQUE (driver_id)
);

-- 10. Driver Wallet Transactions
CREATE TABLE IF NOT EXISTS jippy_driver.driver_wallet_transactions(
    driver_wallet_transactions_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_wallet_id integer NOT NULL,
    order_id character varying(30) NOT NULL,
    cod_amount NUMERIC(10,2) NOT NULL,
    transaction_type character varying(20) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_wallet_transactions_pkey PRIMARY KEY (driver_wallet_transactions_id),
    CONSTRAINT driver_wallet_transactions_fk_key FOREIGN KEY (driver_wallet_id)
        REFERENCES jippy_driver.driver_wallet (driver_wallet_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- 11. Driver Current Location
CREATE TABLE IF NOT EXISTS jippy_driver.driver_current_location(
    driver_location_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    current_location GEOGRAPHY(POINT, 4326),
    is_available BOOLEAN,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_location_pkey PRIMARY KEY (driver_location_id),
    CONSTRAINT driver_location_driver_fk_key FOREIGN KEY (driver_id)
        REFERENCES jippy_driver.driver (driver_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT unique_driver_current_location UNIQUE (driver_id)
);

CREATE INDEX IF NOT EXISTS idx_driver_current_location
ON jippy_driver.driver_current_location USING GIST (current_location);

-- 12. Driver Attendance Logs
CREATE TABLE IF NOT EXISTS jippy_driver.driver_attendance_logs (
    driver_attendance_log_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    status character varying(20) NOT NULL,
    changed_at timestamp without time zone NOT NULL,
    location GEOGRAPHY(POINT, 4326),
    device_id TEXT,
    created_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT driver_attendance_logs_pkey PRIMARY KEY (driver_attendance_log_id),
    CONSTRAINT driver_attendance_logs_driver_fk_key FOREIGN KEY (driver_id)
        REFERENCES jippy_driver.driver (driver_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- 13. Driver Stats
CREATE TABLE IF NOT EXISTS jippy_driver.driver_stats(
    driver_stats_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    work_date DATE DEFAULT CURRENT_DATE,
    first_online timestamp without time zone,
    last_offline timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_stats_pkey PRIMARY KEY (driver_stats_id),
    CONSTRAINT driver_stats_driver_fk_key FOREIGN KEY (driver_id)
        REFERENCES jippy_driver.driver (driver_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT unique_driver_daily_stat UNIQUE (driver_id, work_date)
);

-- 14. Driver Incentive History
CREATE TABLE IF NOT EXISTS jippy_driver.driver_incentive_history(
    driver_incentive_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    curr_date DATE DEFAULT CURRENT_DATE,
    incentive_amount NUMERIC(10, 2) NOT NULL,
    completed_orders_count integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_incentive_history_pkey PRIMARY KEY (driver_incentive_history_id),
    CONSTRAINT driver_incentive_history_driver_fk_key FOREIGN KEY (driver_id)
        REFERENCES jippy_driver.driver (driver_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);